module ExhibitsData
  module Advocates

    def self.full_program_links
      [
        {name: "Who Should Be President?", url: "/catalog/dabe2b-who-should-be-president"},
        {name: "20: Should We Lift Our Embargo on Trade with Castro's Cuba?", url: "/catalog/8c5d4d-should-we-lift-our-embargo-on-trade-with-castro-s-cuba"},
        {name: "30: Should Colleges Adopt A Fixed Rule Expelling Any Student Who Used Obstruction, Sit-ins Or Other Illegal Physical Force As A Means Of Persuasion?", url: "/catalog/5967e4-should-colleges-adopt-a-fixed-rule-expelling-any-student-who-used-obstruction-sit-ins-or-other-illeg"},
        {name: "33: Should Your City Provide Methadone to Heroin Addicts?", url: "/catalog/6c668d-should-your-city-provide-methadone-to-heroin-addicts"},
        {name: "52: Should the Government Adopt Long-Term Wage and Price Controls for Selected Unions and Industries?", url: "/catalog/45a509-should-the-government-adopt-long-term-wage-and-price-controls-for-selected-unions-and-industries"},
        {name: "64: If You Oppose the War, Should You Answer the Call for Massive Civil Disobedience?", url: "/catalog/012c7d-if-you-oppose-the-war-should-you-answer-the-call-for-massive-civil-disobedience"},
        {name: "74: Should The Government Drop The Charges Against Daniel Ellsberg?", url: "/catalog/903d38-should-the-government-drop-the-charges-against-daniel-ellsberg"},
        {name: "78: Should television news be exempt from the fairness doctrine?", url: "/catalog/f199dd-should-television-news-be-exempt-from-the-fairness-doctrine"},
        {name: "82: Should Congress enact a national involuntary commitment program for narcotic addicts?", url: "/catalog/300583-should-congress-enact-a-national-involuntary-commitment-program-for-narcotic-addicts"},
        {name: "83: Should Congress Limit the President's War Powers?", url: "/catalog/8cd064-should-congress-limit-the-president-s-war-powers"},
        {name: "88: Should Courts Be Able To Admit Evidence Police Have Seized Illegally?", url: "/catalog/3102e9-should-courts-be-able-to-admit-evidence-police-have-seized-illegally"},
        {name: "93: Should the Olympics be open to professional athletes?", url: "/catalog/1159a4-should-the-olympics-be-open-to-professional-athletes"},
        {name: "98: Should large corporations be driven out of farming?", url: "/catalog/7873e5-should-large-corporations-be-driven-out-of-farming"},
        {name: "306: Would Justice Be Served Better if a Jury Didn\u0092t Have to be Unanimous to Convict Someone?", url: "/catalog/65e8ab-would-justice-be-served-better-if-a-jury-didn-t-have-to-be-unanimous-to-convict-someone"},
        {name: "307: Should the news media refuse to publish candidate preference polls?", url: "/catalog/e4ea13-should-the-news-media-refuse-to-publish-candidate-preference-polls"},
        {name: "308: Would we be safer from crime if we closed down most of our prisons?", url: "/catalog/8f8260-would-we-be-safer-from-crime-if-we-closed-down-most-of-our-prisons"},
        {name: "310: Should Newsmen be allowed to keep secret their sources of information without fear of jail?", url: "/catalog/9c89de-should-newsmen-be-allowed-to-keep-secret-their-sources-of-information-without-fear-of-jail"},
        {name: "312: Should public use of our national parks be restricted?", url: "/catalog/3169fe-should-public-use-of-our-national-parks-be-restricted"},
        {name: "313: Should Your State Restore the Death Penalty?", url: "/catalog/4723d6-should-your-state-restore-the-death-penalty"},
        {name: "315: Should Drug Advertisements Be Banned From Television", url: "/catalog/003c26-should-drug-advertisements-be-banned-from-television"},
        {name: "316: Should half of the federal dollars reserved for highways be diverted to mass transit systems?", url: "/catalog/9576b8-should-half-of-the-federal-dollars-reserved-for-highways-be-diverted-to-mass-transit-systems"},
        {name: "317: Should Social Security benefits be financed in part from general tax revenues?", url: "/catalog/6d6b72-should-social-security-benefits-be-financed-in-part-from-general-tax-revenues"},
        {name: "319: Should the president spend the money Congress appropriates?", url: "/catalog/ac2585-should-the-president-spend-the-money-congress-appropriates"},
        {name: "323: Should the US immediately develop its oil, coal, and other resources to meet the energy crisis?", url: "/catalog/a249a4-should-the-us-immediately-develop-its-oil-coal-and-other-resources-to-meet-the-energy-crisis"},
        {name: "326: Should the U.S. Government Establish an Independent Consumer Protection Agency?", url: "/catalog/6805e3-should-the-u-s-government-establish-an-independent-consumer-protection-agency"},
        {name: "327: Should the law allow birth control treatment for teenagers without their parents\u0092 consent?", url: "/catalog/5df121-should-the-law-allow-birth-control-treatment-for-teenagers-without-their-parents-consent"},
        {name: "404: Should Your State Adopt a Constitutional Amendment to Limit State Spending?", url: "/catalog/c3ffb5-should-your-state-adopt-a-constitutional-amendment-to-limit-state-spending"},
        {name: "407: Should The President Be Impeached?", url: "/catalog/001e10-should-the-president-be-impeached"},
        {name: "409: Should the United States Press for Israeli Withdrawal From Occupied Territories and Offer to Guarantee Israel's Security?", url: "/catalog/f0394b-should-the-united-states-press-for-israeli-withdrawal-from-occupied-territories-and-offer-to-guarant"},
        {name: "410: Would the Nation be Better Off if Fewer People Went to College", url: "/catalog/83cacd-would-the-nation-be-better-off-if-fewer-people-went-to-college"},
        {name: "412: Should We Rely on Nuclear Power to Help Supply Our Future Emergency Needs?", url: "/catalog/cd71dd-should-we-rely-on-nuclear-power-to-help-supply-our-future-emergency-needs"},
        {name: "413: Should Congress create a federal oil and gas corporation to compete with private industry?", url: "/catalog/b70b3a-should-congress-create-a-federal-oil-and-gas-corporation-to-compete-with-private-industry"},
        {name: "414: Should The Federal Government Subsidize Political Campaigns and Limit Individual Contributions?", url: "/catalog/4297b1-should-the-federal-government-subsidize-political-campaigns-and-limit-individual-contributions"},
        {name: "415: Should We Develop Highly Accurate Missiles and Emphasize Military Targets Rather Than Cities?", url: "/catalog/e97cd3-should-we-develop-highly-accurate-missiles-and-emphasize-military-targets-rather-than-cities"},
        {name: "416: Should All Medical Experiments on Prisoners Be Banned?", url: "/catalog/1ef28c-should-all-medical-experiments-on-prisoners-be-banned"},
        {name: "417: Should Courts Admit Evidence that Police Have Seized Illegally?", url: "/catalog/f51707-should-courts-admit-evidence-that-police-have-seized-illegally"},
        {name: "418: Should Colleges and Universities Give Preferential Admission to Minority Group Applicants?", url: "/catalog/a5ac7b-should-colleges-and-universities-give-preferential-admission-to-minority-group-applicants"},
        {name: "422: Should newspapers be required to give reply space to political candidates and others they have attacked?", url: "/catalog/2806a1-should-newspapers-be-required-to-give-reply-space-to-political-candidates-and-others-they-have-attac"},
        {name: "424: Should Defenses based on Pleas of Insanity be Abolished in Criminal Trials?", url: "/catalog/7cf709-should-defenses-based-on-pleas-of-insanity-be-abolished-in-criminal-trials"},
        {name: "425: Should Marriage Between Homosexuals Be Permitted?", url: "/catalog/f4ae6e-should-marriage-between-homosexuals-be-permitted"},
        {name: "426: Should we limit the size of investments by banks and other large institutions in the stock market?", url: "/catalog/9964d2-should-we-limit-the-size-of-investments-by-banks-and-other-large-institutions-in-the-stock-market"},
        {name: "502: Should the United States Support 'Self-Determination' for Palestinians in a Middle East Peace Settlement?", url: "/catalog/cf45d9-should-the-united-states-support-self-determination-for-palestinians-in-a-middle-east-peace-settleme"},
        {name: "503: Should Congress pass President Carter\u0092s Welfare/Jobs Bill?", url: "/catalog/9ea265-should-congress-pass-president-carter-s-welfare-jobs-bill"},
        {name: "504: Should the federal government guarantee comprehensive medical care for all Americans?", url: "/catalog/fe9d71-should-the-federal-government-guarantee-comprehensive-medical-care-for-all-americans"},
        {name: "506: Should Congress provide more protection for union organizing?", url: "/catalog/cde83c-should-congress-provide-more-protection-for-union-organizing"},
        {name: "507: Should the Federal Government give tax credits to help pay for school tuition?", url: "/catalog/5d5c78-should-the-federal-government-give-tax-credits-to-help-pay-for-school-tuition"},
        {name: "508: Should the Federal Trade Commission Ban Advertising on Children's Television?", url: "/catalog/a5d687-should-the-federal-trade-commission-ban-advertising-on-children-s-television"},
        {name: "511: Should The Federal Government Reduce Everybody\u0092s Income Tax Thirty Percent Over The Next Three Years?", url: "/catalog/04982a-should-the-federal-government-reduce-everybody-s-income-tax-thirty-percent-over-the-next-three-years"},
        {name: "601: Should United States foreign policy include covert action by the CIA?", url: "/catalog/d42c41-should-united-states-foreign-policy-include-covert-action-by-the-cia"},
        {name: "602: Should Journalists have the right to protect their sources?", url: "/catalog/a67a24-should-journalists-have-the-right-to-protect-their-sources"},
        {name: "605: Should Congress Deregulate Trucking?", url: "/catalog/540844-should-congress-deregulate-trucking"},
        {name: "606: Should The U.S. Agree To United Nations Control Of Undersea Mining?", url: "/catalog/09ccea-should-the-u-s-agree-to-united-nations-control-of-undersea-mining"},
        {name: "607: Should we end the courts\u0092 authority over truant, runaway and incorrigible children?", url: "/catalog/b10434-should-we-end-the-courts-authority-over-truant-runaway-and-incorrigible-children"},
        {name: "608: Should there be a constitutional amendment requiring a balanced federal budget?", url: "/catalog/21c0fc-should-there-be-a-constitutional-amendment-requiring-a-balanced-federal-budget"},
        {name: "609: Should Congress substantially increase federal funding for public broadcasting?", url: "/catalog/e8cba7-should-congress-substantially-increase-federal-funding-for-public-broadcasting"},
        {name: "610: Should we have a compulsory system of service for all young Americans?", url: "/catalog/40307a-should-we-have-a-compulsory-system-of-service-for-all-young-americans"},
        {name: "611: Should we cut back veteran\u0092s preference for state and federal jobs to provide more opportunities for women?", url: "/catalog/249620-should-we-cut-back-veteran-s-preference-for-state-and-federal-jobs-to-provide-more-opportunities-for"},
        {name: "612: Should Puerto Rico Become a State, a Commonwealth, or an Independent Nation?", url: "/catalog/2e1010-should-puerto-rico-become-a-state-a-commonwealth-or-an-independent-nation"},
        {name: "613: Should We Stop Construction Of Nuclear Power Plants?", url: "/catalog/b9a2ac-should-we-stop-construction-of-nuclear-power-plants"},
        {name: "614: Should your state assume financial control of its public schools?", url: "/catalog/83457c-should-your-state-assume-financial-control-of-its-public-schools"},
        {name: "616: Should We Impose Mandatory Controls On Wages, Prices and Profits?", url: "/catalog/3ff8c3-should-we-impose-mandatory-controls-on-wages-prices-and-profits"},
        {name: "618: Should Your State Carry Out Death Sentences?", url: "/catalog/706fa7-should-your-state-carry-out-death-sentences"},
        {name: "619: Should we legalize marijuana?", url: "/catalog/05cb09-should-we-legalize-marijuana"}
      ]
    end
  end
end