module ExhibitsData
  module NewTelevisionWorkshop
    def self.complete_collection_links
      [
        {:name=>"21", :url=>"/catalog/openvault:44126"},
        {:name=>"37/73", :url=>"/catalog/openvault:25878"},
        {:name=>"9/23", :url=>"/catalog/openvault:21693"},
        {:name=>"Aeros", :url=>"/catalog/openvault:44146"},
        {:name=>"America, Inc.", :url=>"/catalog/openvault:16904"},
        {:name=>"Art Talker", :url=>"/catalog/openvault:19291"},
        {:name=>"Art of Memory", :url=>"/catalog/openvault:12111"},
        {:name=>"Artist in the Seventies, An: Peter Campus", :url=>"/catalog/openvault:10022"},
        {:name=>"Artists Babies Bodies", :url=>"/catalog/openvault:28344"},
        {:name=>"Artists on Artists", :url=>"/catalog/openvault:15152"},
        {:name=>"As Quiet As", :url=>"/catalog/openvault:18857"},
        {:name=>"As Seen On TV", :url=>"/catalog/openvault:28162"},
        {:name=>"As if Memories Could Deceive Me", :url=>"/catalog/openvault:17051"},
        {:name=>"Aviary", :url=>"/catalog/openvault:44063"},
        {:name=>"Ballplayer", :url=>"/catalog/openvault:44029"},
        {:name=>"Bartending at the Two O'Clock", :url=>"/catalog/openvault:44154"},
        {:name=>"Batteries Not Included", :url=>"/catalog/openvault:14704"},
        {:name=>"Bees and Thoroughbreds", :url=>"/catalog/openvault:44117"},
        {:name=>"Belladonna", :url=>"/catalog/openvault:44076"},
        {:name=>"Berlin/Nilreb: Tourist Journal", :url=>"/catalog/openvault:44026"},
        {:name=>"Big Inning, The", :url=>"/catalog/openvault:43991"},
        {:name=>"Bill Viola's Reverse Television", :url=>"/catalog/openvault:44010"},
        {:name=>"Bill Viola's Space Between the Teeth", :url=>"/catalog/openvault:44084"},
        {:name=>"Binge", :url=>"/catalog/openvault:44072"},
        {:name=>"Bob's Master", :url=>"/catalog/openvault:9281"},
        {:name=>"Branda Miller's Time Squared", :url=>"/catalog/openvault:43960"},
        {:name=>"Bruce Cronin and Babe Sargent", :url=>"/catalog/openvault:43936"},
        {:name=>"Bruce and Babe", :url=>"/catalog/openvault:22288"},
        {:name=>"California Casual", :url=>"/catalog/openvault:19630"},
        {:name=>"California One", :url=>"/catalog/openvault:25663"},
        {:name=>"Capoeira of Brazil", :url=>"/catalog/openvault:21523"},
        {:name=>"Capoeiras of Bahia Dance Company performs capoeira", :url=>"/catalog/openvault:44058"},
        {:name=>"Car wash sequence from Easy Living", :url=>"/catalog/openvault:44024"},
        {:name=>"Celebrate: A Time to Dance", :url=>"/catalog/openvault:17367"},
        {:name=>"Changing Steps", :url=>"/catalog/openvault:43987"},
        {:name=>"Chant A Capella", :url=>"/catalog/openvault:21275"},
        {:name=>"Charles Blessing Interview", :url=>"/catalog/openvault:23179"},
        {:name=>"Charlie Smith and the Fritter Tree", :url=>"/catalog/openvault:27988"},
        {:name=>"City Archives", :url=>"/catalog/openvault:12780"},
        {:name=>"City Motion Space Game", :url=>"/catalog/openvault:6421"},
        {:name=>"Cityscape", :url=>"/catalog/openvault:24232"},
        {:name=>"Coffee Coloured Children", :url=>"/catalog/openvault:44080"},
        {:name=>"Collisions", :url=>"/catalog/openvault:18377"},
        {:name=>"Collisions (Louis Falco)", :url=>"/catalog/openvault:28357"},
        {:name=>"Color Schemes", :url=>"/catalog/openvault:44042"},
        {:name=>"Common Mistakes", :url=>"/catalog/openvault:39252"},
        {:name=>"Confessions of a Chameleon", :url=>"/catalog/openvault:44085"},
        {:name=>"Damnation of Faust: Charming Landscape", :url=>"/catalog/openvault:44068"},
        {:name=>"Damnation of Faust: Will-O'-the-Wisp (A Deceitful Goal)", :url=>"/catalog/openvault:43928"},
        {:name=>"Dance in Open Spaces", :url=>"/catalog/openvault:8810"},
        {:name=>"Dance of Darkness", :url=>"/catalog/openvault:44069"},
        {:name=>"Dance sequence from Mountain View", :url=>"/catalog/openvault:44035"},
        {:name=>"Dancers, Buildings, and People in the Street", :url=>"/catalog/openvault:42726"},
        {:name=>"Dances: Remy Charlip", :url=>"/catalog/openvault:28043"},
        {:name=>"Desire, Inc.", :url=>"/catalog/openvault:44031"},
        {:name=>"Digital Speech", :url=>"/catalog/openvault:23836"},
        {:name=>"Dinner Party: A Semi-Buffet", :url=>"/catalog/openvault:21163"},
        {:name=>"District 1", :url=>"/catalog/openvault:12517"},
        {:name=>"Dogs, The", :url=>"/catalog/openvault:44152"},
        {:name=>"Double Lunar Dogs", :url=>"/catalog/openvault:10922"},
        {:name=>"Double Take", :url=>"/catalog/openvault:29359"},
        {:name=>"Dream Moments", :url=>"/catalog/openvault:24426"},
        {:name=>"Dreamworks", :url=>"/catalog/openvault:11025"},
        {:name=>"East Ended Tape", :url=>"/catalog/openvault:7835"},
        {:name=>"Easy Living", :url=>"/catalog/openvault:23874"},
        {:name=>"Edit 1", :url=>"/catalog/openvault:20003"},
        {:name=>"Ellis Island", :url=>"/catalog/openvault:21832"},
        {:name=>"Ena's Adventures, Part II", :url=>"/catalog/openvault:33046"},
        {:name=>"Event Horizon", :url=>"/catalog/openvault:26058"},
        {:name=>"Four Sided Tape", :url=>"/catalog/openvault:7059"},
        {:name=>"Four Songs", :url=>"/catalog/openvault:21251"},
        {:name=>"Frank: A Vietnam Veteran", :url=>"/catalog/openvault:6690"},
        {:name=>"From An Island Summer", :url=>"/catalog/openvault:7327"},
        {:name=>"Gallery Piece, The", :url=>"/catalog/openvault:6857"},
        {:name=>"Galway Kinnell reads Wait", :url=>"/catalog/openvault:44107"},
        {:name=>"Ganapati: A Spirit in the Bush", :url=>"/catalog/openvault:36303"},
        {:name=>"George Rochberg and His Music", :url=>"/catalog/openvault:21895"},
        {:name=>"George's House", :url=>"/catalog/openvault:6048"},
        {:name=>"Glow Worm by Remy Charlip", :url=>"/catalog/openvault:44001"},
        {:name=>"Going Away Party, The", :url=>"/catalog/openvault:43977"},
        {:name=>"Gray Hairs", :url=>"/catalog/openvault:13984"},
        {:name=>"Great American Fourth of July and Other Disasters, The", :url=>"/catalog/openvault:20057"},
        {:name=>"Great Frontier, The", :url=>"/catalog/openvault:43980"},
        {:name=>"Gus Solomans performs City Motion Space Game", :url=>"/catalog/openvault:43938"},
        {:name=>"Hall's Crossing", :url=>"/catalog/openvault:44147"},
        {:name=>"Harry Somers and His Music", :url=>"/catalog/openvault:23051"},
        {:name=>"Hart Island", :url=>"/catalog/openvault:43957"},
        {:name=>"Hazardous Hootenanny", :url=>"/catalog/openvault:41042"},
        {:name=>"High Hot Moons", :url=>"/catalog/openvault:14814"},
        {:name=>"Houses that Are Left, The", :url=>"/catalog/openvault:43927"},
        {:name=>"I Do Not Know What It Is that I Am Like", :url=>"/catalog/openvault:44055"},
        {:name=>"I Want Some Insecticide", :url=>"/catalog/openvault:21686"},
        {:name=>"I Wish I Might", :url=>"/catalog/openvault:19670"},
        {:name=>"Images Diffused by Time", :url=>"/catalog/openvault:44131"},
        {:name=>"Images Diffused by Time", :url=>"/catalog/openvault:10914"},
        {:name=>"Imaginary Crossing", :url=>"/catalog/openvault:7300"},
        {:name=>"In the Blink of an Eye, Amphibian Dreams... If I Could Fly, I Would Fly", :url=>"/catalog/openvault:44087"},
        {:name=>"In the Rehearsal Room", :url=>"/catalog/openvault:10494"},
        {:name=>"Inertia", :url=>"/catalog/openvault:22715"},
        {:name=>"Inhabitant of Another Place", :url=>"/catalog/openvault:5783"},
        {:name=>"Interpolation", :url=>"/catalog/openvault:7733"},
        {:name=>"Irony", :url=>"/catalog/openvault:12646"},
        {:name=>"J. S. Bach", :url=>"/catalog/openvault:37748"},
        {:name=>"Joan Jonas in Double Lunar Dogs", :url=>"/catalog/openvault:43929"},
        {:name=>"John Cage performs 4:33", :url=>"/catalog/openvault:43958"},
        {:name=>"Joseph Schwantner and His Music", :url=>"/catalog/openvault:8067"},
        {:name=>"Judy Chicago Interview", :url=>"/catalog/openvault:22136"},
        {:name=>"Karkador; Phrenology ", :url=>"/catalog/openvault:30590"},
        {:name=>"L'Image", :url=>"/catalog/openvault:10165"},
        {:name=>"Lauf der Dinge, Der", :url=>"/catalog/openvault:31606"},
        {:name=>"Lea Grammont", :url=>"/catalog/openvault:19088"},
        {:name=>"Lee Krasner Interview", :url=>"/catalog/openvault:17863"},
        {:name=>"Lotte Goslar's Pantomime Circus", :url=>"/catalog/openvault:11856"},
        {:name=>"Louis Zukofsky", :url=>"/catalog/openvault:6272"},
        {:name=>"Lown Ranjer Aind Tontow, The", :url=>"/catalog/openvault:28686"},
        {:name=>"Lucille Clifton reads Turning", :url=>"/catalog/openvault:44108"},
        {:name=>"Lulu Smith: The Chicken That Ate Columbus", :url=>"/catalog/openvault:6769"},
        {:name=>"Made in Maine", :url=>"/catalog/openvault:28737"},
        {:name=>"Magritte sur la Plage", :url=>"/catalog/openvault:12213"},
        {:name=>"Man Ray, Man Ray", :url=>"/catalog/openvault:43969"},
        {:name=>"Marta Renzi in You Little Wild Heart", :url=>"/catalog/openvault:44006"},
        {:name=>"Mary Feldhaus Weber's I Wish I Might", :url=>"/catalog/openvault:43981"},
        {:name=>"Meaning of the Interval", :url=>"/catalog/openvault:44077"},
        {:name=>"Medium Is the Medium, The", :url=>"/catalog/openvault:35848"},
        {:name=>"Melanie Kahane Interview", :url=>"/catalog/openvault:17335"},
        {:name=>"Memories of the Vietnam War", :url=>"/catalog/openvault:44098"},
        {:name=>"Meredith Monk's Ellis Island", :url=>"/catalog/openvault:44156"},
        {:name=>"Meredith Monk's Turtle Dreams", :url=>"/catalog/openvault:43935"},
        {:name=>"Mike Kelley in Evol", :url=>"/catalog/openvault:44110"},
        {:name=>"Modern Times", :url=>"/catalog/openvault:22392"},
        {:name=>"More TV Stories", :url=>"/catalog/openvault:27430"},
        {:name=>"Mother's Little Network", :url=>"/catalog/openvault:24678"},
        {:name=>"Mountain View", :url=>"/catalog/openvault:27359"},
        {:name=>"Music Image Workshop: Tristan and Isolde", :url=>"/catalog/openvault:37231"},
        {:name=>"Music of Ivana Themmen, The", :url=>"/catalog/openvault:6304"},
        {:name=>"Music of Joan Tower, The", :url=>"/catalog/openvault:22076"},
        {:name=>"Music of Lukas Foss, The", :url=>"/catalog/openvault:16823"},
        {:name=>"Music of Michael Colgrass, The", :url=>"/catalog/openvault:21246"},
        {:name=>"Music of Ralph Shapey, The", :url=>"/catalog/openvault:15480"},
        {:name=>"My Puberty", :url=>"/catalog/openvault:44091"},
        {:name=>"Myth of Modern Dance, The", :url=>"/catalog/openvault:15463"},
        {:name=>"Nam June Paik's 9/23", :url=>"/catalog/openvault:43932"},
        {:name=>"Nam June Paik's Electronic Opera #1", :url=>"/catalog/openvault:43944"},
        {:name=>"New England Fishermen", :url=>"/catalog/openvault:17774"},
        {:name=>"New Television, Episode 110", :url=>"/catalog/openvault:21302"},
        {:name=>"New Television, Episode 111", :url=>"/catalog/openvault:27013"},
        {:name=>"New Television, Episode 201", :url=>"/catalog/openvault:20543"},
        {:name=>"New Television, Episode 202", :url=>"/catalog/openvault:13745"},
        {:name=>"New Television, Episode 203", :url=>"/catalog/openvault:20782"},
        {:name=>"New Television, Episode 204", :url=>"/catalog/openvault:21489"},
        {:name=>"New Television, Episode 301", :url=>"/catalog/openvault:14318"},
        {:name=>"New Television, Episode 302", :url=>"/catalog/openvault:13165"},
        {:name=>"New Television, Episode 303", :url=>"/catalog/openvault:8345"},
        {:name=>"New Television, Episode 304", :url=>"/catalog/openvault:16785"},
        {:name=>"New Television, Episode 305", :url=>"/catalog/openvault:24305"},
        {:name=>"New Television, Episode 306", :url=>"/catalog/openvault:10100"},
        {:name=>"New Television, Episode 307", :url=>"/catalog/openvault:15600"},
        {:name=>"New Television, Episode 308", :url=>"/catalog/openvault:16649"},
        {:name=>"New Television, Episode 309", :url=>"/catalog/openvault:9196"},
        {:name=>"New Television, Episode 310", :url=>"/catalog/openvault:20546"},
        {:name=>"New Television, Episode 311", :url=>"/catalog/openvault:15746"},
        {:name=>"New Television, Episode 312", :url=>"/catalog/openvault:11289"},
        {:name=>"New Television, Episode 401", :url=>"/catalog/openvault:18264"},
        {:name=>"New Television, Episode 402", :url=>"/catalog/openvault:26410"},
        {:name=>"New Television, Episode 403", :url=>"/catalog/openvault:12578"},
        {:name=>"New Television, Episode 405", :url=>"/catalog/openvault:14636"},
        {:name=>"New Television, Episode 406", :url=>"/catalog/openvault:26595"},
        {:name=>"New Television, Episode 407", :url=>"/catalog/openvault:16026"},
        {:name=>"New Television, Episode 408", :url=>"/catalog/openvault:26819"},
        {:name=>"New Television, Episode 409", :url=>"/catalog/openvault:13395"},
        {:name=>"New Television, Episode 410", :url=>"/catalog/openvault:22538"},
        {:name=>"New Television, Episode 411", :url=>"/catalog/openvault:7718"},
        {:name=>"New Television, Episode 412", :url=>"/catalog/openvault:7799"},
        {:name=>"New Television, Episode 413", :url=>"/catalog/openvault:11362"},
        {:name=>"New Television, Episode 501", :url=>"/catalog/openvault:22519"},
        {:name=>"New Television, Episode 506", :url=>"/catalog/openvault:26985"},
        {:name=>"New Television, Episode 508", :url=>"/catalog/openvault:20211"},
        {:name=>"New Television, Episode 509", :url=>"/catalog/openvault:17040"},
        {:name=>"New Television, Episode 510", :url=>"/catalog/openvault:12968"},
        {:name=>"New Television, Episode 511", :url=>"/catalog/openvault:20306"},
        {:name=>"New Television, Episode 512", :url=>"/catalog/openvault:10454"},
        {:name=>"New Television, Episode 513", :url=>"/catalog/openvault:17657"},
        {:name=>"New Television, Episode 601", :url=>"/catalog/openvault:14363"},
        {:name=>"New Television, Episode 603", :url=>"/catalog/openvault:5825"},
        {:name=>"New Television, Episode 605", :url=>"/catalog/openvault:21793"},
        {:name=>"New Television, Episode 606", :url=>"/catalog/openvault:28419"},
        {:name=>"New Television, Episode 607", :url=>"/catalog/openvault:11538"},
        {:name=>"New Television, Episode 608", :url=>"/catalog/openvault:16417"},
        {:name=>"New Television, Episode 610", :url=>"/catalog/openvault:23739"},
        {:name=>"New Television, Episode 611", :url=>"/catalog/openvault:7182"},
        {:name=>"New Television, Episode 613", :url=>"/catalog/openvault:15786"},
        {:name=>"Nine Heroes", :url=>"/catalog/openvault:25492"},
        {:name=>"O Panama", :url=>"/catalog/openvault:39003"},
        {:name=>"O'Neil Ford Interview", :url=>"/catalog/openvault:15457"},
        {:name=>"Observations on Photography", :url=>"/catalog/openvault:24371"},
        {:name=>"One Way", :url=>"/catalog/openvault:13973"},
        {:name=>"Opening sequence from As Seen on TV", :url=>"/catalog/openvault:44158"},
        {:name=>"Opening sequence from Set and Reset, Version 1", :url=>"/catalog/openvault:44040"},
        {:name=>"Pale Cool, Pale Warm", :url=>"/catalog/openvault:8614"},
        {:name=>"Past Fantasies", :url=>"/catalog/openvault:21679"},
        {:name=>"Paul Rand Interview", :url=>"/catalog/openvault:10145"},
        {:name=>"Phantom of the Open Hearth", :url=>"/catalog/openvault:14146"},
        {:name=>"Plage Concrete", :url=>"/catalog/openvault:43931"},
        {:name=>"Poetry Breaks I, Allen Ginsberg", :url=>"/catalog/openvault:17770"},
        {:name=>"Poetry Breaks I, Galway Kinnell", :url=>"/catalog/openvault:12215"},
        {:name=>"Poetry Breaks I, Martin Espada", :url=>"/catalog/openvault:17468"},
        {:name=>"Poetry Breaks I, Robert Bly", :url=>"/catalog/openvault:19533"},
        {:name=>"Poetry Breaks I, Ruth Stone", :url=>"/catalog/openvault:7459"},
        {:name=>"Poetry Breaks I, Seamus Heaney", :url=>"/catalog/openvault:24654"},
        {:name=>"Poetry Breaks I, Sharon Olds", :url=>"/catalog/openvault:28396"},
        {:name=>"Poetry Breaks II, Cyrus Cassells", :url=>"/catalog/openvault:8731"},
        {:name=>"Poetry Breaks II, Li-Young Lee", :url=>"/catalog/openvault:26348"},
        {:name=>"Poetry Breaks II, Lucille Clifton", :url=>"/catalog/openvault:5712"},
        {:name=>"Poetry Breaks II, Stanley Kunitz", :url=>"/catalog/openvault:14127"},
        {:name=>"Poetry Breaks II, Thylias Moss", :url=>"/catalog/openvault:6823"},
        {:name=>"Poetry Breaks III, Charles Simic", :url=>"/catalog/openvault:25583"},
        {:name=>"Poetry Breaks III, Dennis Nurkse", :url=>"/catalog/openvault:20519"},
        {:name=>"Poetry Breaks III, Philip Levine", :url=>"/catalog/openvault:28169"},
        {:name=>"Poetry Breaks for Schools and Libraries: Charles Simic", :url=>"/catalog/openvault:17992"},
        {:name=>"Poetry Breaks for Schools and Libraries: D. Nurkse", :url=>"/catalog/openvault:25500"},
        {:name=>"Poetry Breaks for Schools and Libraries: Galway Kinnell", :url=>"/catalog/openvault:25850"},
        {:name=>"Poetry Breaks for Schools and Libraries: Lucille Clifton", :url=>"/catalog/openvault:5995"},
        {:name=>"Poetry Breaks for Schools and Libraries: Martin Espada", :url=>"/catalog/openvault:10738"},
        {:name=>"Poetry Breaks for Schools and Libraries: Philip Levine", :url=>"/catalog/openvault:25725"},
        {:name=>"Portraits from the Two O'Clock", :url=>"/catalog/openvault:7240"},
        {:name=>"Primordial Soup", :url=>"/catalog/openvault:11101"},
        {:name=>"Proposition, The", :url=>"/catalog/openvault:17249"},
        {:name=>"Put Blood in the Music", :url=>"/catalog/openvault:42768"},
        {:name=>"Quarks", :url=>"/catalog/openvault:7438"},
        {:name=>"Quickening", :url=>"/catalog/openvault:35443"},
        {:name=>"Quidditas", :url=>"/catalog/openvault:26954"},
        {:name=>"Return of the Motherland", :url=>"/catalog/openvault:44159"},
        {:name=>"Reverie, The", :url=>"/catalog/openvault:16315"},
        {:name=>"Reverse Television", :url=>"/catalog/openvault:6661"},
        {:name=>"Ritual Clowns", :url=>"/catalog/openvault:33463"},
        {:name=>"Robert Bly reads Loon's Cry", :url=>"/catalog/openvault:44104"},
        {:name=>"Romance of the Angel of Lions", :url=>"/catalog/openvault:13796"},
        {:name=>"Ros Barron", :url=>"/catalog/openvault:6475"},
        {:name=>"Ros Barron's Headgame.", :url=>"/catalog/openvault:44054"},
        {:name=>"Ros Barron's Lea Grammont", :url=>"/catalog/openvault:44095"},
        {:name=>"Ros Barron's Magriitte sur la Plage", :url=>"/catalog/openvault:44039"},
        {:name=>"Roseland Recollections", :url=>"/catalog/openvault:44025"},
        {:name=>"Rotary Action", :url=>"/catalog/openvault:43971"},
        {:name=>"Royal Flesh", :url=>"/catalog/openvault:12833"},
        {:name=>"Russell Connor's Art Talker", :url=>"/catalog/openvault:44136"},
        {:name=>"Selected Works, William Wegman, 1973-1974", :url=>"/catalog/openvault:38893"},
        {:name=>"Set and Reset, Version 1", :url=>"/catalog/openvault:19452"},
        {:name=>"Set of Coincidence", :url=>"/catalog/openvault:10032"},
        {:name=>"Since you asked.., with Galway Kinnell", :url=>"/catalog/openvault:43961"},
        {:name=>"Since you asked.., with Lucille Clifton", :url=>"/catalog/openvault:43923"},
        {:name=>"Slott Opera", :url=>"/catalog/openvault:10577"},
        {:name=>"Small Jubilee, A", :url=>"/catalog/openvault:29968"},
        {:name=>"Son of Sam and Delilah", :url=>"/catalog/openvault:44073"},
        {:name=>"Split Britches", :url=>"/catalog/openvault:43998"},
        {:name=>"Stan Vanderbeek's Violence Sonata", :url=>"/catalog/openvault:44165"},
        {:name=>"Star Crossed Romance of Josephine Cosnowski, The", :url=>"/catalog/openvault:21778"},
        {:name=>"Storm and Stress", :url=>"/catalog/openvault:44122"},
        {:name=>"Strange Space", :url=>"/catalog/openvault:12085"},
        {:name=>"Sudden Difficulties", :url=>"/catalog/openvault:24851"},
        {:name=>"Summer Dances", :url=>"/catalog/openvault:9765"},
        {:name=>"Sun, Moon and Feather", :url=>"/catalog/openvault:37640"},
        {:name=>"Survival Ecology - Hamburger Harmonics", :url=>"/catalog/openvault:11260"},
        {:name=>"Teleportraits", :url=>"/catalog/openvault:22431"},
        {:name=>"The Forbidden Channel", :url=>"/catalog/openvault:44020"},
        {:name=>"The Luckiest Fisherman", :url=>"/catalog/openvault:44092"},
        {:name=>"Thomas Randazza talks about seasickness", :url=>"/catalog/openvault:44096"},
        {:name=>"Three Transitions", :url=>"/catalog/openvault:24786"},
        {:name=>"Time Code", :url=>"/catalog/openvault:28334"},
        {:name=>"Time Squared", :url=>"/catalog/openvault:16454"},
        {:name=>"Tribute to John Cage, A", :url=>"/catalog/openvault:12388"},
        {:name=>"Trisha and Carmen", :url=>"/catalog/openvault:44017"},
        {:name=>"Turtle Dreams", :url=>"/catalog/openvault:14017"},
        {:name=>"Tzaddik", :url=>"/catalog/openvault:8456"},
        {:name=>"Very First Half-Inch Videotape Festival Ever, The", :url=>"/catalog/openvault:7546"},
        {:name=>"Video Commune (Beatles From Beginning To End)", :url=>"/catalog/openvault:16504"},
        {:name=>"Video Portrait: Robert Rauschenberg", :url=>"/catalog/openvault:13537"},
        {:name=>"Video Variations", :url=>"/catalog/openvault:6810"},
        {:name=>"Video playback is explained to Russell Connor", :url=>"/catalog/openvault:43947"},
        {:name=>"Violence Sonata", :url=>"/catalog/openvault:20397"},
        {:name=>"Volcano Saga", :url=>"/catalog/openvault:43986"},
        {:name=>"Walking Up", :url=>"/catalog/openvault:16896"},
        {:name=>"Walter Robinson and His Music", :url=>"/catalog/openvault:16385"},
        {:name=>"Water Catalogue, The", :url=>"/catalog/openvault:19543"},
        {:name=>"Watermotor for Dancer and Camera", :url=>"/catalog/openvault:44016"},
        {:name=>"Way Downtown", :url=>"/catalog/openvault:32767"},
        {:name=>"What You Mean We?", :url=>"/catalog/openvault:18617"},
        {:name=>"William Wegman and Man Ray", :url=>"/catalog/openvault:44071"},
        {:name=>"William Wegman explains the rules of photography", :url=>"/catalog/openvault:44149"},
        {:name=>"William Wegman's \"Dinner Party\"", :url=>"/catalog/openvault:44018"},
        {:name=>"Winter Notebook; Lines Of Force", :url=>"/catalog/openvault:37823"},
        {:name=>"World of Photography, The", :url=>"/catalog/openvault:17179"},
        {:name=>"You Little Wild Heart", :url=>"/catalog/openvault:14111"},
        {:name=>"Zone in Three Parts", :url=>"/catalog/openvault:22798"}
      ]
    end

    def self.artists_showcase_links
      [
        {:name=>"37/73", :url=>"/catalog/openvault:25878"},
        {:name=>"Art Talker", :url=>"/catalog/openvault:19291"},
        {:name=>"Artists Babies Bodies", :url=>"/catalog/openvault:28344"},
        {:name=>"Artists on Artists", :url=>"/catalog/openvault:15152"},
        {:name=>"Batteries Not Included", :url=>"/catalog/openvault:14704"},
        {:name=>"Bill Viola's Space Between the Teeth", :url=>"/catalog/openvault:44084"},
        {:name=>"Bob's Master", :url=>"/catalog/openvault:9281"},
        {:name=>"California Casual", :url=>"/catalog/openvault:19630"},
        {:name=>"California One", :url=>"/catalog/openvault:25663"},
        {:name=>"Celebrate: A Time to Dance", :url=>"/catalog/openvault:17367"},
        {:name=>"Chant A Capella", :url=>"/catalog/openvault:21275"},
        {:name=>"City Archives", :url=>"/catalog/openvault:12780"},
        {:name=>"Dinner Party: A Semi-Buffet", :url=>"/catalog/openvault:21163"},
        {:name=>"East Ended Tape", :url=>"/catalog/openvault:7835"},
        {:name=>"Edit 1", :url=>"/catalog/openvault:20003"},
        {:name=>"Four Sided Tape", :url=>"/catalog/openvault:7059"},
        {:name=>"Four Songs", :url=>"/catalog/openvault:21251"},
        {:name=>"Gallery Piece, The", :url=>"/catalog/openvault:6857"},
        {:name=>"Gray Hairs", :url=>"/catalog/openvault:13984"},
        {:name=>"In the Rehearsal Room", :url=>"/catalog/openvault:10494"},
        {:name=>"Inertia", :url=>"/catalog/openvault:22715"},
        {:name=>"Interpolation", :url=>"/catalog/openvault:7733"},
        {:name=>"Lea Grammont", :url=>"/catalog/openvault:19088"},
        {:name=>"Louis Zukofsky", :url=>"/catalog/openvault:6272"},
        {:name=>"Man Ray, Man Ray", :url=>"/catalog/openvault:43969"},
        {:name=>"Modern Times", :url=>"/catalog/openvault:22392"},
        {:name=>"Past Fantasies", :url=>"/catalog/openvault:21679"},
        {:name=>"Primordial Soup", :url=>"/catalog/openvault:11101"},
        {:name=>"Quarks", :url=>"/catalog/openvault:7438"},
        {:name=>"Quidditas", :url=>"/catalog/openvault:26954"},
        {:name=>"Romance of the Angel of Lions", :url=>"/catalog/openvault:13796"},
        {:name=>"Ros Barron's Lea Grammont", :url=>"/catalog/openvault:44095"},
        {:name=>"Russell Connor's Art Talker", :url=>"/catalog/openvault:44136"},
        {:name=>"Selected Works, William Wegman, 1973-1974", :url=>"/catalog/openvault:38893"},
        {:name=>"Set of Coincidence", :url=>"/catalog/openvault:10032"},
        {:name=>"Slott Opera", :url=>"/catalog/openvault:10577"},
        {:name=>"Survival Ecology - Hamburger Harmonics", :url=>"/catalog/openvault:11260"},
        {:name=>"Teleportraits", :url=>"/catalog/openvault:22431"},
        {:name=>"Three Transitions", :url=>"/catalog/openvault:24786"},
        {:name=>"Video Portrait: Robert Rauschenberg", :url=>"/catalog/openvault:13537"},
        {:name=>"William Wegman and Man Ray", :url=>"/catalog/openvault:44071"},
        {:name=>"William Wegman's \"Dinner Party\"", :url=>"/catalog/openvault:44018"},
        {:name=>"Winter Notebook; Lines Of Force", :url=>"/catalog/openvault:37823"}
      ]
    end

    def self.frames_of_reference_links
      [
        {:name=>"37/73", :url=>"/catalog/openvault:25878"},
        {:name=>"Artist in the Seventies, An: Peter Campus", :url=>"/catalog/openvault:10022"},
        {:name=>"As Quiet As", :url=>"/catalog/openvault:18857"},
        {:name=>"Bartending at the Two O'Clock", :url=>"/catalog/openvault:44154"},
        {:name=>"Bruce Cronin and Babe Sargent", :url=>"/catalog/openvault:43936"},
        {:name=>"Bruce and Babe", :url=>"/catalog/openvault:22288"},
        {:name=>"Capoeira of Brazil", :url=>"/catalog/openvault:21523"},
        {:name=>"Capoeiras of Bahia Dance Company performs capoeira", :url=>"/catalog/openvault:44058"},
        {:name=>"Cityscape", :url=>"/catalog/openvault:24232"},
        {:name=>"Collisions (Louis Falco)", :url=>"/catalog/openvault:28357"},
        {:name=>"Dance in Open Spaces", :url=>"/catalog/openvault:8810"},
        {:name=>"Dances: Remy Charlip", :url=>"/catalog/openvault:28043"},
        {:name=>"Dream Moments", :url=>"/catalog/openvault:24426"},
        {:name=>"Dreamworks", :url=>"/catalog/openvault:11025"},
        {:name=>"Ellis Island", :url=>"/catalog/openvault:21832"},
        {:name=>"Event Horizon", :url=>"/catalog/openvault:26058"},
        {:name=>"Glow Worm by Remy Charlip", :url=>"/catalog/openvault:44001"},
        {:name=>"High Hot Moons", :url=>"/catalog/openvault:14814"},
        {:name=>"Images Diffused by Time", :url=>"/catalog/openvault:44131"},
        {:name=>"Images Diffused by Time", :url=>"/catalog/openvault:10914"},
        {:name=>"Imaginary Crossing", :url=>"/catalog/openvault:7300"},
        {:name=>"Lulu Smith: The Chicken That Ate Columbus", :url=>"/catalog/openvault:6769"},
        {:name=>"Marta Renzi in You Little Wild Heart", :url=>"/catalog/openvault:44006"},
        {:name=>"Meredith Monk's Ellis Island", :url=>"/catalog/openvault:44156"},
        {:name=>"Observations on Photography", :url=>"/catalog/openvault:24371"},
        {:name=>"One Way", :url=>"/catalog/openvault:13973"},
        {:name=>"Portraits from the Two O'Clock", :url=>"/catalog/openvault:7240"},
        {:name=>"Reverie, The", :url=>"/catalog/openvault:16315"},
        {:name=>"Ros Barron", :url=>"/catalog/openvault:6475"},
        {:name=>"Walking Up", :url=>"/catalog/openvault:16896"},
        {:name=>"You Little Wild Heart", :url=>"/catalog/openvault:14111"}
      ]
    end
  end
end