module ExhibitsData
  module SayBrother
    def self.complete_collection_links
      [
        {:name=>"1968-1978,  Where Do We Go From Here?", :url=>"catalog/openvault:17478"},
        {:name=>"A.B. Spellman comments on the pardon granted to President Richard Nixon", :url=>"catalog/openvault:44150"},
        {:name=>"A.L.D. (African Liberation Day)", :url=>"catalog/openvault:26630"},
        {:name=>"Action for Boston Community Development", :url=>"catalog/openvault:44099"},
        {:name=>"Affirmative Action or Discrimination", :url=>"catalog/openvault:17276"},
        {:name=>"Affirmative Action or Discrimination Pt 2", :url=>"catalog/openvault:16437"},
        {:name=>"Africa: An Overview", :url=>"catalog/openvault:6731"},
        {:name=>"African American youth and education in Boston", :url=>"catalog/openvault:43939"},
        {:name=>"African Americans and the United States judicial system", :url=>"catalog/openvault:44139"},
        {:name=>"African Artist, The", :url=>"catalog/openvault:11703"},
        {:name=>"African Derivations", :url=>"catalog/openvault:8636"},
        {:name=>"African Liberation", :url=>"catalog/openvault:23599"},
        {:name=>"African Liberation Committee Film", :url=>"catalog/openvault:17385"},
        {:name=>"African Liberation Day Focus", :url=>"catalog/openvault:10175"},
        {:name=>"Afro-Studies: Why So Many Barriers?", :url=>"catalog/openvault:20356"},
        {:name=>"Aggrery Mbere interview", :url=>"catalog/openvault:44127"},
        {:name=>"Aggrey Mbere on life under Apartheid", :url=>"catalog/openvault:44101"},
        {:name=>"Al Jarreau performs \"You Don't See Me\"", :url=>"catalog/openvault:43651"},
        {:name=>"Alternative Medicine", :url=>"catalog/openvault:17563"},
        {:name=>"Alvin Pouissant on the rise of Black on Black murders", :url=>"catalog/openvault:44140"},
        {:name=>"Ancient African Kingdoms", :url=>"catalog/openvault:26525"},
        {:name=>"Ancient African Kingdoms", :url=>"catalog/openvault:16752"},
        {:name=>"Andrew Young discusses local political involvement in the community", :url=>"catalog/openvault:43951"},
        {:name=>"Angela Paige Cook comments on standardized testing", :url=>"catalog/openvault:44004"},
        {:name=>"Angeles Rodriguez comments on funding problems in human services", :url=>"catalog/openvault:43919"},
        {:name=>"Another Approach To Theatre", :url=>"catalog/openvault:12027"},
        {:name=>"Another Conversation with the Next Generation", :url=>"catalog/openvault:16583"},
        {:name=>"Answer from the State House, An", :url=>"catalog/openvault:6685"},
        {:name=>"Art of Photography, The", :url=>"catalog/openvault:11105"},
        {:name=>"Asian Pacific Heritage Celebration", :url=>"catalog/openvault:23073"},
        {:name=>"Assassination of Amilcar Cabral", :url=>"catalog/openvault:43983"},
        {:name=>"Attica", :url=>"catalog/openvault:18580"},
        {:name=>"Attica", :url=>"catalog/openvault:14977"},
        {:name=>"Australian Aborigines", :url=>"catalog/openvault:7351"},
        {:name=>"Australian aborigines visit Franklin Park", :url=>"catalog/openvault:44160"},
        {:name=>"Barbara Barrow comments on Judge Garrity's altered desegregation plan", :url=>"catalog/openvault:43959"},
        {:name=>"Basketball Clinic", :url=>"catalog/openvault:23018"},
        {:name=>"Ben Lee comments on employment in Chinatown garment industry", :url=>"catalog/openvault:43913"},
        {:name=>"Best of 1976 - 1977", :url=>"catalog/openvault:11097"},
        {:name=>"Beverly Smith redefines politics in light of the feminist movement", :url=>"catalog/openvault:44044"},
        {:name=>"Bilingual Education", :url=>"catalog/openvault:8869"},
        {:name=>"Black Arts", :url=>"catalog/openvault:23450"},
        {:name=>"Black Athlete, The", :url=>"catalog/openvault:22649"},
        {:name=>"Black Business", :url=>"catalog/openvault:25364"},
        {:name=>"Black Colleges", :url=>"catalog/openvault:24460"},
        {:name=>"Black Fraternal Organizations", :url=>"catalog/openvault:17915"},
        {:name=>"Black History Week", :url=>"catalog/openvault:22213"},
        {:name=>"Black Nativity", :url=>"catalog/openvault:44038"},
        {:name=>"Black Politics", :url=>"catalog/openvault:6251"},
        {:name=>"Black Power on University Campuses", :url=>"catalog/openvault:8828"},
        {:name=>"Black Repertory Company", :url=>"catalog/openvault:19013"},
        {:name=>"Black Solidarity Day", :url=>"catalog/openvault:7440"},
        {:name=>"Black Solidarity Day 1972", :url=>"catalog/openvault:43956"},
        {:name=>"Black Stars", :url=>"catalog/openvault:15115"},
        {:name=>"Black Woman", :url=>"catalog/openvault:26064"},
        {:name=>"Black Women and the E.R.A.", :url=>"catalog/openvault:8933"},
        {:name=>"Black Youth and Education", :url=>"catalog/openvault:36635"},
        {:name=>"Blast From the Past with Cleve Sellers", :url=>"catalog/openvault:44141"},
        {:name=>"Blast From the Past with Jesse Jackson", :url=>"catalog/openvault:44062"},
        {:name=>"Blast From the Past with actor Julian Mayfield", :url=>"catalog/openvault:43953"},
        {:name=>"Blast From the Past with poet and playwright Amiri Baraka", :url=>"catalog/openvault:44060"},
        {:name=>"Blast from the Past with Chico Neblett", :url=>"catalog/openvault:43985"},
        {:name=>"Blast from the Past with FCC Commissioner Benjamin Hooks", :url=>"catalog/openvault:43914"},
        {:name=>"Blast from the Past with Raymond St. Jacques", :url=>"catalog/openvault:43968"},
        {:name=>"Blast from the Past with Rhody McCoy", :url=>"catalog/openvault:43979"},
        {:name=>"Blast from the Past with musician Jerry Iceman Butler", :url=>"catalog/openvault:44066"},
        {:name=>"Blast from the Past with vocalist Miriam Makeba", :url=>"catalog/openvault:44011"},
        {:name=>"Blues Ain't Nothing But a Poem, The", :url=>"catalog/openvault:25701"},
        {:name=>"Bobby Seale interview", :url=>"catalog/openvault:43942"},
        {:name=>"Boston Art Ensemble perform in the Say Brother Studio", :url=>"catalog/openvault:44048"},
        {:name=>"Boston based artists discuss the meaning of Black art", :url=>"catalog/openvault:44037"},
        {:name=>"Boston teenagers discuss the Darryl Williams shooting", :url=>"catalog/openvault:43943"},
        {:name=>"Brenda Verner comments on women's rights movement", :url=>"catalog/openvault:44124"},
        {:name=>"Brown Sugar in concert", :url=>"catalog/openvault:44123"},
        {:name=>"Button Up Your Overcoat, pt. 2", :url=>"catalog/openvault:17430"},
        {:name=>"Button Up Your Overcoat, pt.1", :url=>"catalog/openvault:17429"},
        {:name=>"Can the Sun Be Your Enemy", :url=>"catalog/openvault:27280"},
        {:name=>"Candid Look at Boston's Largest Black Radio Station, A", :url=>"catalog/openvault:28115"},
        {:name=>"Cannonball Adderley and the Cannonball Express", :url=>"catalog/openvault:44133"},
        {:name=>"Cannonball Express", :url=>"catalog/openvault:11063"},
        {:name=>"Carew Film Festival", :url=>"catalog/openvault:17527"},
        {:name=>"Caring for Your Health", :url=>"catalog/openvault:16950"},
        {:name=>"Caroline Hunter comments on the struggle for African liberation", :url=>"catalog/openvault:44166"},
        {:name=>"Carribean", :url=>"catalog/openvault:25494"},
        {:name=>"Case of Justice, A", :url=>"catalog/openvault:16188"},
        {:name=>"Case of Justice, A (Pt. 2)", :url=>"catalog/openvault:13023"},
        {:name=>"Cast members discuss the The Wiz, based on L. Frank Baum's Wizard of Oz", :url=>"catalog/openvault:43965"},
        {:name=>"Cecil Taylor interview", :url=>"catalog/openvault:43933"},
        {:name=>"Celebrate 76", :url=>"catalog/openvault:6216"},
        {:name=>"Celebrate the Year of the Horse", :url=>"catalog/openvault:26817"},
        {:name=>"Changing Face of Chinatown, The", :url=>"catalog/openvault:11471"},
        {:name=>"Christmas in Color", :url=>"catalog/openvault:12848"},
        {:name=>"Chuck Turner interview", :url=>"catalog/openvault:44051"},
        {:name=>"Clif Saunders discusses self-determination in the Native American community", :url=>"catalog/openvault:43976"},
        {:name=>"Community Access", :url=>"catalog/openvault:14133"},
        {:name=>"Community Fellows", :url=>"catalog/openvault:5748"},
        {:name=>"Community Organization", :url=>"catalog/openvault:23775"},
        {:name=>"Community in Action", :url=>"catalog/openvault:13626"},
        {:name=>"Concerts in Black and Brown", :url=>"catalog/openvault:27401"},
        {:name=>"Consumerism", :url=>"catalog/openvault:15211"},
        {:name=>"Conversation with the Next Generation, A", :url=>"catalog/openvault:9132"},
        {:name=>"Cooper Community Center", :url=>"catalog/openvault:44109"},
        {:name=>"Copps Hill Burial Ground", :url=>"catalog/openvault:44032"},
        {:name=>"Cost of a Facelift", :url=>"catalog/openvault:17425"},
        {:name=>"Creation of the Mashpee District in 1685", :url=>"catalog/openvault:44128"},
        {:name=>"Crucian Fiesta 1980", :url=>"catalog/openvault:20507"},
        {:name=>"Current News", :url=>"catalog/openvault:20000"},
        {:name=>"Curtis Mayfield and The Impressions perform \"We're A Winner\"", :url=>"catalog/openvault:44002"},
        {:name=>"D.A.N.C.E.", :url=>"catalog/openvault:15715"},
        {:name=>"David O. Ives discusses the origin of Say Brother on WGBH Television", :url=>"catalog/openvault:43945"},
        {:name=>"David Sakura recalls life in Japanese detention camps in the United States during World War II", :url=>"catalog/openvault:44145"},
        {:name=>"Day with Muhammad Ali, A", :url=>"catalog/openvault:28150"},
        {:name=>"Deal with China, A", :url=>"catalog/openvault:16581"},
        {:name=>"Dealin' with African drummer Babatunde Olatunji", :url=>"catalog/openvault:44021"},
        {:name=>"Dealin' with poet and Pan African supporter Haki Madhubuti", :url=>"catalog/openvault:43994"},
        {:name=>"Demonstration of martial arts swordplay", :url=>"catalog/openvault:43948"},
        {:name=>"Desegregation", :url=>"catalog/openvault:17593"},
        {:name=>"Development of education systems in the Caribbean", :url=>"catalog/openvault:44030"},
        {:name=>"Dick Lane remembers Dinah Washington", :url=>"catalog/openvault:44082"},
        {:name=>"Dinah Washington", :url=>"catalog/openvault:18378"},
        {:name=>"Dinizulu Kamau and Abdullah Khalil Sabree comment on the Hakim Jamal murder case", :url=>"catalog/openvault:43949"},
        {:name=>"Dinizulu Kamau discusses violence against inmates in the Departmental Segregation Unit (DSU), 10 Block", :url=>"catalog/openvault:43995"},
        {:name=>"Discrimination and racism in the construction community", :url=>"catalog/openvault:43926"},
        {:name=>"Dismissing Some Myths About Chinese Americans", :url=>"catalog/openvault:6907"},
        {:name=>"Distortions of Black Life", :url=>"catalog/openvault:6532"},
        {:name=>"Diversifying the job base in the Chinese American community", :url=>"catalog/openvault:44075"},
        {:name=>"Divisiveness within the Black community", :url=>"catalog/openvault:43982"},
        {:name=>"Documenting African American history", :url=>"catalog/openvault:44135"},
        {:name=>"Dr. Emillio Carillo comments on healthcare in the Latino community", :url=>"catalog/openvault:43966"},
        {:name=>"Dream Deferred, A", :url=>"catalog/openvault:16520"},
        {:name=>"E.L. Jones performs Othello", :url=>"catalog/openvault:43970"},
        {:name=>"Eartha Kitt talks about her early childhood", :url=>"catalog/openvault:44070"},
        {:name=>"Economic Development of the Chinese Community", :url=>"catalog/openvault:10595"},
        {:name=>"Ed Redd and Raymond Jordan debate why most African Americans are Democrats", :url=>"catalog/openvault:43934"},
        {:name=>"Education", :url=>"catalog/openvault:21217"},
        {:name=>"Educational Workshop", :url=>"catalog/openvault:12854"},
        {:name=>"Elma Lewis 25th Anniversary Celebration", :url=>"catalog/openvault:25477"},
        {:name=>"Elma Lewis reads the poem \"Sympathy\" by Paul Lawrence Dunbar", :url=>"catalog/openvault:44033"},
        {:name=>"Elma Lewis: Black Poetry For Children", :url=>"catalog/openvault:25271"},
        {:name=>"End to experimental school project in Boston", :url=>"catalog/openvault:43993"},
        {:name=>"Eritrean People's Liberation Front", :url=>"catalog/openvault:43999"},
        {:name=>"Ethnic history of Puerto Rico", :url=>"catalog/openvault:44053"},
        {:name=>"Eva Jessye: Black American Folk Music", :url=>"catalog/openvault:44112"},
        {:name=>"Evening with Eartha Kitt, An", :url=>"catalog/openvault:26306"},
        {:name=>"Evening with Melvin Van Peebles and Dick Gregory", :url=>"catalog/openvault:17935"},
        {:name=>"Everett Goodwin reads from his poem To A Down and Out Brother", :url=>"catalog/openvault:44121"},
        {:name=>"Excursion with Tumbao, An", :url=>"catalog/openvault:18058"},
        {:name=>"Experimental Tv", :url=>"catalog/openvault:16984"},
        {:name=>"Face of Love, The", :url=>"catalog/openvault:13716"},
        {:name=>"Falling standards in Boston Public Schools", :url=>"catalog/openvault:44065"},
        {:name=>"Fashion Fun", :url=>"catalog/openvault:19188"},
        {:name=>"Federal Laws and the Native American: Patterns of Paper Politics", :url=>"catalog/openvault:14833"},
        {:name=>"Feelings of exclusion from the political process in the African American Community", :url=>"catalog/openvault:44086"},
        {:name=>"Folktales", :url=>"catalog/openvault:26085"},
        {:name=>"Football", :url=>"catalog/openvault:21527"},
        {:name=>"For Colored Girls Who Have Considered Suicide / When the Rainbow is not Enuf", :url=>"catalog/openvault:44046"},
        {:name=>"Framingham: Who's Gonna Take the Weight?", :url=>"catalog/openvault:25629"},
        {:name=>"Franz Minuty discusses voodooism", :url=>"catalog/openvault:44163"},
        {:name=>"From Puerto Rico's Point of View", :url=>"catalog/openvault:8685"},
        {:name=>"Gambia, The, part II", :url=>"catalog/openvault:16643"},
        {:name=>"Great, Great Grandmothers", :url=>"catalog/openvault:15379"},
        {:name=>"Gregory Spence comments on new testing criteria for students", :url=>"catalog/openvault:44009"},
        {:name=>"Guinea Bissau", :url=>"catalog/openvault:21258"},
        {:name=>"Guinea Bissau Conflict", :url=>"catalog/openvault:44049"},
        {:name=>"Health Care", :url=>"catalog/openvault:13390"},
        {:name=>"Health Update", :url=>"catalog/openvault:8194"},
        {:name=>"Henry F. Owens, III, comments on the death of Levi Hart", :url=>"catalog/openvault:44164"},
        {:name=>"Henry Johnson comments on significance of the 1972 African Liberation Day March", :url=>"catalog/openvault:44148"},
        {:name=>"Highland Park Free School", :url=>"catalog/openvault:43975"},
        {:name=>"Hilda Harris performs Bizet's The Segadilla", :url=>"catalog/openvault:44000"},
        {:name=>"Historical justifications for the institution of slavery", :url=>"catalog/openvault:44090"},
        {:name=>"History of Black Capitalism in the United States", :url=>"catalog/openvault:43924"},
        {:name=>"History of Chinese Americans in Massachusetts", :url=>"catalog/openvault:44093"},
        {:name=>"Hottest Seat in Town, The", :url=>"catalog/openvault:23568"},
        {:name=>"Hour with Marcia Ann Gillespie, An", :url=>"catalog/openvault:16368"},
        {:name=>"Howlin' Wolf", :url=>"catalog/openvault:22369"},
        {:name=>"Howlin' Wolf in concert", :url=>"catalog/openvault:44074"},
        {:name=>"Hustlers, Drugs and Prison", :url=>"catalog/openvault:27914"},
        {:name=>"Image of Women in African Art", :url=>"catalog/openvault:25515"},
        {:name=>"In the Matter of Levi Hart", :url=>"catalog/openvault:14291"},
        {:name=>"Incident at Cass Lake", :url=>"catalog/openvault:19252"},
        {:name=>"Indian Child Welfare Act", :url=>"catalog/openvault:43973"},
        {:name=>"Inside Women Inside", :url=>"catalog/openvault:13525"},
        {:name=>"Interview with Billy Wilson", :url=>"catalog/openvault:43997"},
        {:name=>"Interview with Buddy Guy and Junior Wells", :url=>"catalog/openvault:43990"},
        {:name=>"Interview with Howard Hughes of the Dimock Community Health Center", :url=>"catalog/openvault:44057"},
        {:name=>"Interview with Tom Satch Sanders", :url=>"catalog/openvault:44067"},
        {:name=>"Interview with blues and folk singer Elizabeth Cotten", :url=>"catalog/openvault:44111"},
        {:name=>"Interview with poet Nikki Giovanni", :url=>"catalog/openvault:44094"},
        {:name=>"Invitation From Cuba", :url=>"catalog/openvault:18916"},
        {:name=>"Is Photography a valid art form", :url=>"catalog/openvault:44008"},
        {:name=>"Island in America, An", :url=>"catalog/openvault:19424"},
        {:name=>"Islands, The", :url=>"catalog/openvault:6676"},
        {:name=>"Jazz", :url=>"catalog/openvault:16324"},
        {:name=>"Jean McGuire on the need for a greater supply of African American teachers", :url=>"catalog/openvault:44142"},
        {:name=>"Jerry Cummings interview", :url=>"catalog/openvault:44138"},
        {:name=>"Jim Cooper reads Why Apes Look Like People", :url=>"catalog/openvault:44106"},
        {:name=>"Jim Yee comments on commercial development of Park Plaza and Lafayette Place", :url=>"catalog/openvault:44045"},
        {:name=>"Joe Manong discusses his flight from South Africa", :url=>"catalog/openvault:43946"},
        {:name=>"John Bryant criticizes the Boston School Committee", :url=>"catalog/openvault:44007"},
        {:name=>"Joseph Monserrat interview", :url=>"catalog/openvault:43955"},
        {:name=>"Joseph Nelson reminsices about Josephine Baker", :url=>"catalog/openvault:43962"},
        {:name=>"June Cross Special Report on desegregation", :url=>"catalog/openvault:43988"},
        {:name=>"Kwanzaa", :url=>"catalog/openvault:14308"},
        {:name=>"Kwanzaa Special", :url=>"catalog/openvault:12013"},
        {:name=>"Lack of equal opportunities for African American women in the workplace", :url=>"catalog/openvault:43940"},
        {:name=>"Lack of minority representation in the jury system", :url=>"catalog/openvault:44155"},
        {:name=>"Lack of services available to women prisoners", :url=>"catalog/openvault:43937"},
        {:name=>"Larry Johnson and Jack Jackson perform \"John Henry\"", :url=>"catalog/openvault:44079"},
        {:name=>"Law Clinic", :url=>"catalog/openvault:25020"},
        {:name=>"Law In the Community", :url=>"catalog/openvault:28274"},
        {:name=>"Leadership in the Black Community", :url=>"catalog/openvault:18681"},
        {:name=>"Lest We Forget: Martin Luther King, A Retrospective", :url=>"catalog/openvault:12333"},
        {:name=>"Local reaction to the New Bedford protests", :url=>"catalog/openvault:44005"},
        {:name=>"Local residents comment on political candidates", :url=>"catalog/openvault:43930"},
        {:name=>"Local residents comment on the cost of living", :url=>"catalog/openvault:44102"},
        {:name=>"Look Into the Past, A", :url=>"catalog/openvault:15856"},
        {:name=>"Look at Cuba, A", :url=>"catalog/openvault:5904"},
        {:name=>"Look at Eritrea, A", :url=>"catalog/openvault:25712"},
        {:name=>"Looking at Ourselves: How the Black Media Watches Boston", :url=>"catalog/openvault:18663"},
        {:name=>"Louis Farrakhan", :url=>"catalog/openvault:17613"},
        {:name=>"Lyle Lane discusses mutual exchange program between United States and Cuba", :url=>"catalog/openvault:44003"},
        {:name=>"Malcolm X", :url=>"catalog/openvault:37563"},
        {:name=>"Marcia Ann Gillespie on affirmative action for women in the workplace", :url=>"catalog/openvault:43918"},
        {:name=>"Mario Valdes discusses Black divinities", :url=>"catalog/openvault:43954"},
        {:name=>"Martin Luther King Jr.'s March on Washington", :url=>"catalog/openvault:44105"},
        {:name=>"Mashpee Indian lawsuit against the Commonwealth of Massachusetts", :url=>"catalog/openvault:43967"},
        {:name=>"Mashpee Quest", :url=>"catalog/openvault:24354"},
        {:name=>"Mass. Black History", :url=>"catalog/openvault:19892"},
        {:name=>"Maya Angelou reads her poem \"Phenomenal Women\"", :url=>"catalog/openvault:43925"},
        {:name=>"Mel King on Ray Richardson", :url=>"catalog/openvault:44103"},
        {:name=>"Melnea Cass Interview", :url=>"catalog/openvault:44144"},
        {:name=>"Melvin Van Peebles interview", :url=>"catalog/openvault:44129"},
        {:name=>"Men and Women", :url=>"catalog/openvault:27569"},
        {:name=>"Middle Passage", :url=>"catalog/openvault:23079"},
        {:name=>"Minority Cultural Institutions: Programmed to Fail?", :url=>"catalog/openvault:15331"},
        {:name=>"Mississippi Fred MacDowell", :url=>"catalog/openvault:44019"},
        {:name=>"Modification of Phase Two: What Does It Really Mean?", :url=>"catalog/openvault:18291"},
        {:name=>"Moment for Music, A", :url=>"catalog/openvault:22577"},
        {:name=>"Momodou Ceesay talks about the function of an artist", :url=>"catalog/openvault:44036"},
        {:name=>"Montgomery to Memphis", :url=>"catalog/openvault:26428"},
        {:name=>"Muhammad Ali and the Vietnam War", :url=>"catalog/openvault:44034"},
        {:name=>"Muhammad Ali press conference at the Elma Lewis School of Fine Arts", :url=>"catalog/openvault:44132"},
        {:name=>"Music Special", :url=>"catalog/openvault:25232"},
        {:name=>"Mystic Chain", :url=>"catalog/openvault:6500"},
        {:name=>"NAACP", :url=>"catalog/openvault:15573"},
        {:name=>"Nation of Islam: A Portrait", :url=>"catalog/openvault:19350"},
        {:name=>"National Black Political Convention", :url=>"catalog/openvault:19958"},
        {:name=>"Native American Foster Care", :url=>"catalog/openvault:13072"},
        {:name=>"Negro Masonry in the United States", :url=>"catalog/openvault:43922"},
        {:name=>"New Bedford", :url=>"catalog/openvault:21003"},
        {:name=>"New Music", :url=>"catalog/openvault:24579"},
        {:name=>"New Music", :url=>"catalog/openvault:13995"},
        {:name=>"Nia Anderson performs in The Commitment", :url=>"catalog/openvault:44041"},
        {:name=>"Night of the Blues, A", :url=>"catalog/openvault:15380"},
        {:name=>"Normalization of relations with Communist China", :url=>"catalog/openvault:43984"},
        {:name=>"Observations of Brown Brilliance", :url=>"catalog/openvault:13277"},
        {:name=>"Odetta", :url=>"catalog/openvault:15062"},
        {:name=>"Oh My God, Mama King Is Dead", :url=>"catalog/openvault:27131"},
        {:name=>"Old, Black and Alive", :url=>"catalog/openvault:11702"},
        {:name=>"Old, Black and Alive", :url=>"catalog/openvault:28218"},
        {:name=>"Orchestra Pabon in concert", :url=>"catalog/openvault:44050"},
        {:name=>"Our Aboriginal Brothers", :url=>"catalog/openvault:19737"},
        {:name=>"Owusu Sadaukai urges boycott of goods from African Countries", :url=>"catalog/openvault:43989"},
        {:name=>"Paige Academy: An Alternative Education", :url=>"catalog/openvault:6555"},
        {:name=>"Panel discussion of Black Power on University Campuses", :url=>"catalog/openvault:44014"},
        {:name=>"Panel discussion on violence against women", :url=>"catalog/openvault:44081"},
        {:name=>"Percussions", :url=>"catalog/openvault:6647"},
        {:name=>"Perspectives in Politics with Royal Bolling and Mel King", :url=>"catalog/openvault:11039"},
        {:name=>"Philip Hart discusses the history of the New School for Children and Roxbury Community College", :url=>"catalog/openvault:43912"},
        {:name=>"Pianist Randy Weston performs \"The Healers\"", :url=>"catalog/openvault:44125"},
        {:name=>"Plans to restructure the Boston School Committee", :url=>"catalog/openvault:44153"},
        {:name=>"Playing from the Music Malcolm Wrote", :url=>"catalog/openvault:44157"},
        {:name=>"Poet Larry Roland performs live in the Say Brother studio", :url=>"catalog/openvault:44167"},
        {:name=>"Poetry and Arts", :url=>"catalog/openvault:11120"},
        {:name=>"Poetry in Motion", :url=>"catalog/openvault:7887"},
        {:name=>"Point of View, A", :url=>"catalog/openvault:6773"},
        {:name=>"Polaroid in South Africa", :url=>"catalog/openvault:9098"},
        {:name=>"Politics of Women's Healthcare, The", :url=>"catalog/openvault:15979"},
        {:name=>"Portrayal of women in African art", :url=>"catalog/openvault:44064"},
        {:name=>"Praise to King Martin", :url=>"catalog/openvault:25590"},
        {:name=>"Press Conference", :url=>"catalog/openvault:19161"},
        {:name=>"Prison Reforms", :url=>"catalog/openvault:16329"},
        {:name=>"Profile of Boston's Chinese Community, A", :url=>"catalog/openvault:8030"},
        {:name=>"Profile of Latino Social Service Agencies, A", :url=>"catalog/openvault:7660"},
        {:name=>"Public Housing", :url=>"catalog/openvault:19673"},
        {:name=>"Que Pasa? Don't Ask If You Don't Want to Know", :url=>"catalog/openvault:27144"},
        {:name=>"Racial mix of welfare recipients in the United States", :url=>"catalog/openvault:44168"},
        {:name=>"Racial stereotyping in 19th Century trade cards", :url=>"catalog/openvault:44013"},
        {:name=>"Racism in the United States Army during the Vietnam War", :url=>"catalog/openvault:44120"},
        {:name=>"Racism in the feminist community", :url=>"catalog/openvault:43963"},
        {:name=>"Ralph H. Metcalfe on the Panama Canal", :url=>"catalog/openvault:44118"},
        {:name=>"Randall Robinson Comments on Ways to Oppose Apartheid", :url=>"catalog/openvault:44083"},
        {:name=>"Rapping with the Bluenotes", :url=>"catalog/openvault:13421"},
        {:name=>"Reflections of Senegal", :url=>"catalog/openvault:18193"},
        {:name=>"Regents of the University of California v. Bakke case", :url=>"catalog/openvault:44130"},
        {:name=>"Reggae: A Caribbean Cultural Explosion", :url=>"catalog/openvault:9853"},
        {:name=>"Relationship between African Americans and the two party system", :url=>"catalog/openvault:43917"},
        {:name=>"Remembering the Savoy Cafe", :url=>"catalog/openvault:44043"},
        {:name=>"Response from South Africa, A", :url=>"catalog/openvault:6417"},
        {:name=>"Retirement facilities for elderly African Americans", :url=>"catalog/openvault:44056"},
        {:name=>"Ricardo Austrich on cutting all ties between Cuba and the United States", :url=>"catalog/openvault:44088"},
        {:name=>"Rise of Minority Affairs reporting in the United States", :url=>"catalog/openvault:44116"},
        {:name=>"Robert Lenzner uncovers the Polaroid scandal in South Africa", :url=>"catalog/openvault:43992"},
        {:name=>"Role of Independent African Countries in the United Nations", :url=>"catalog/openvault:44134"},
        {:name=>"Role of students in the creation African American Studies Programs", :url=>"catalog/openvault:44047"},
        {:name=>"Ron Karenga and the origin of Kwanzaa", :url=>"catalog/openvault:44028"},
        {:name=>"Ronald Ingram Gospel chorus", :url=>"catalog/openvault:43974"},
        {:name=>"Ronnie Laws and Pressure", :url=>"catalog/openvault:8552"},
        {:name=>"Ronnie Laws talks about his early musical influences", :url=>"catalog/openvault:44114"},
        {:name=>"Roots Music", :url=>"catalog/openvault:10554"},
        {:name=>"Rudy Pierce interview", :url=>"catalog/openvault:43916"},
        {:name=>"Saim Kinte recalls his first meeting with Alex Haley", :url=>"catalog/openvault:44151"},
        {:name=>"Sanola", :url=>"catalog/openvault:44143"},
        {:name=>"Say Brother 15th Anniversary Gala Celebration", :url=>"catalog/openvault:23798"},
        {:name=>"Say Brother 1st Anniversary Show", :url=>"catalog/openvault:26031"},
        {:name=>"Say Brother News #1", :url=>"catalog/openvault:24506"},
        {:name=>"Say Brother News #2", :url=>"catalog/openvault:19099"},
        {:name=>"Say Brother Pays Tribute to Webster Lewis with a Night on the Town", :url=>"catalog/openvault:14831"},
        {:name=>"Say Brother Presents Message to the People featuring Brown Sugar", :url=>"catalog/openvault:19564"},
        {:name=>"Say Brother commentary on the current penal system", :url=>"catalog/openvault:44119"},
        {:name=>"Say Sister: A Tribute to Third World Women", :url=>"catalog/openvault:12749"},
        {:name=>"Scenes from the 1980 St .Croix carnival", :url=>"catalog/openvault:44089"},
        {:name=>"School Desegregation", :url=>"catalog/openvault:15813"},
        {:name=>"School Issue, The", :url=>"catalog/openvault:13150"},
        {:name=>"Senior Citizens", :url=>"catalog/openvault:12518"},
        {:name=>"Sheryl B. Graves interview", :url=>"catalog/openvault:44061"},
        {:name=>"Should Puerto Rico become the 51st state?", :url=>"catalog/openvault:44059"},
        {:name=>"Sixto Escobar talks about the cultural importance of folk music", :url=>"catalog/openvault:43972"},
        {:name=>"Slave Trade", :url=>"catalog/openvault:12125"},
        {:name=>"Slices of Black Theatre", :url=>"catalog/openvault:15792"},
        {:name=>"Slices of Life", :url=>"catalog/openvault:18123"},
        {:name=>"Social Control", :url=>"catalog/openvault:27823"},
        {:name=>"Solar Visions", :url=>"catalog/openvault:26271"},
        {:name=>"Solar Visions performing live in Say Brother studio", :url=>"catalog/openvault:44023"},
        {:name=>"Something About the Blues", :url=>"catalog/openvault:7922"},
        {:name=>"Sonia Sanchez on the teachings of the Nation of Islam", :url=>"catalog/openvault:43978"},
        {:name=>"South Africa", :url=>"catalog/openvault:7153"},
        {:name=>"South Africa", :url=>"catalog/openvault:16591"},
        {:name=>"South Africa: Perception and Reality", :url=>"catalog/openvault:5821"},
        {:name=>"South West Corridor Land Development Project", :url=>"catalog/openvault:44027"},
        {:name=>"Spikes to Spindles", :url=>"catalog/openvault:16262"},
        {:name=>"Spirit of Umoja", :url=>"catalog/openvault:14262"},
        {:name=>"Spring Special", :url=>"catalog/openvault:13825"},
        {:name=>"State Recognition After 400 Years: Who and Why?", :url=>"catalog/openvault:17896"},
        {:name=>"Street Dancers Bash", :url=>"catalog/openvault:13880"},
        {:name=>"Street Dancers Bash rehearsing the song \"Runnin\"", :url=>"catalog/openvault:44052"},
        {:name=>"Struggle in South Africa", :url=>"catalog/openvault:21119"},
        {:name=>"Sunfire perform \"Soka Jame\" in the Say Brother studio", :url=>"catalog/openvault:43915"},
        {:name=>"Superfly", :url=>"catalog/openvault:44161"},
        {:name=>"Survival on Mother's Island", :url=>"catalog/openvault:11862"},
        {:name=>"Tavares", :url=>"catalog/openvault:18737"},
        {:name=>"Teachings of the Honorable Elijah Muhammad", :url=>"catalog/openvault:43996"},
        {:name=>"Teenagers discuss youth marriage in the Say Brother studio", :url=>"catalog/openvault:43952"},
        {:name=>"Television Violence and Its Effect on Children", :url=>"catalog/openvault:8380"},
        {:name=>"Ten Great Black Historical Figures", :url=>"catalog/openvault:24542"},
        {:name=>"The Art of Black Dance and Music perform dances from the harvest festival Kwanzaa", :url=>"catalog/openvault:44015"},
        {:name=>"The Earth is a Perfect Mother by Ron Skenandore", :url=>"catalog/openvault:44078"},
        {:name=>"The Role of Black Journalists", :url=>"catalog/openvault:44162"},
        {:name=>"The classical heritage of African American musicians", :url=>"catalog/openvault:44100"},
        {:name=>"The death of Steve Biko", :url=>"catalog/openvault:44012"},
        {:name=>"The debate about bilingual education in America", :url=>"catalog/openvault:43921"},
        {:name=>"The meaning of Kwanzaa", :url=>"catalog/openvault:44097"},
        {:name=>"Theatre and the Arts", :url=>"catalog/openvault:21345"},
        {:name=>"Themba Vilakazi discusses the apartheid regime in South Africa", :url=>"catalog/openvault:43941"},
        {:name=>"There Is Always Another Way: A Mind Is a Terrible Thing to Waste", :url=>"catalog/openvault:12912"},
        {:name=>"Third World Potpourri", :url=>"catalog/openvault:27068"},
        {:name=>"Tom Satch Sanders teaches basketball to African American children", :url=>"catalog/openvault:43964"},
        {:name=>"Tribute to Jazz Week, A", :url=>"catalog/openvault:25115"},
        {:name=>"Tribute to Martin Luther King Jr., A", :url=>"catalog/openvault:6074"},
        {:name=>"United Nations", :url=>"catalog/openvault:19610"},
        {:name=>"Unspoken segregation in Boston public schools", :url=>"catalog/openvault:44115"},
        {:name=>"Unsuspected Killers, The", :url=>"catalog/openvault:23242"},
        {:name=>"Value of the Black Vote", :url=>"catalog/openvault:24750"},
        {:name=>"Vaudeville", :url=>"catalog/openvault:16855"},
        {:name=>"Vietnam", :url=>"catalog/openvault:16743"},
        {:name=>"Vignette on the struggle to find employment", :url=>"catalog/openvault:43950"},
        {:name=>"Violence on Women", :url=>"catalog/openvault:23220"},
        {:name=>"Voting irregularities in black polling places", :url=>"catalog/openvault:43920"},
        {:name=>"Walpole: An Examination of Why", :url=>"catalog/openvault:11753"},
        {:name=>"Walpole: An Examination of Why", :url=>"catalog/openvault:43741"},
        {:name=>"Walpole: Every Which Way But Loose", :url=>"catalog/openvault:12195"},
        {:name=>"Walter Leonard", :url=>"catalog/openvault:21880"},
        {:name=>"Walter Leonard talks about the purpose of Affirmative Action programs", :url=>"catalog/openvault:44113"},
        {:name=>"Welfare Controversy, The", :url=>"catalog/openvault:11935"},
        {:name=>"Western Nations failure to censure South Africa", :url=>"catalog/openvault:44137"},
        {:name=>"What is Concilio?", :url=>"catalog/openvault:17955"},
        {:name=>"Who is Topper Carew?", :url=>"catalog/openvault:9393"},
        {:name=>"Winter Special", :url=>"catalog/openvault:26057"},
        {:name=>"Women", :url=>"catalog/openvault:18784"},
        {:name=>"[NO TITLE AVAILABLE]", :url=>"catalog/openvault:44022"}
      ]
    end

    def self.civil_rights_collection_links
      [
        {:name=>"Black Power on University Campuses", :url=>"catalog/openvault:8828"},
        {:name=>"Bobby Seale interview", :url=>"catalog/openvault:43942"},
        {:name=>"John Bryant criticizes the Boston School Committee", :url=>"catalog/openvault:44007"},
        {:name=>"Lest We Forget: Martin Luther King, A Retrospective", :url=>"catalog/openvault:12333"},
        {:name=>"Local reaction to the New Bedford protests", :url=>"catalog/openvault:44005"},
        {:name=>"Malcolm X", :url=>"catalog/openvault:37563"},
        {:name=>"Martin Luther King Jr.'s March on Washington", :url=>"catalog/openvault:44105"},
        {:name=>"Montgomery to Memphis", :url=>"catalog/openvault:26428"},
        {:name=>"NAACP", :url=>"catalog/openvault:15573"},
        {:name=>"New Bedford", :url=>"catalog/openvault:21003"},
        {:name=>"Panel discussion of Black Power on University Campuses", :url=>"catalog/openvault:44014"},
        {:name=>"Praise to King Martin", :url=>"catalog/openvault:25590"},
        {:name=>"Tribute to Martin Luther King Jr., A", :url=>"catalog/openvault:6074"}
      ]
    end

    def self.music_performances_links
      [
        {:name=>"Al Jarreau performs \"You Don't See Me\"", :url=>"catalog/openvault:43651"},
        {:name=>"Another Approach To Theatre", :url=>"catalog/openvault:12027"},
        {:name=>"Black Arts", :url=>"catalog/openvault:23450"},
        {:name=>"Black Solidarity Day", :url=>"catalog/openvault:7440"},
        {:name=>"Black Youth and Education", :url=>"catalog/openvault:36635"},
        {:name=>"Boston Art Ensemble perform in the Say Brother Studio", :url=>"catalog/openvault:44048"},
        {:name=>"Brown Sugar in concert", :url=>"catalog/openvault:44123"},
        {:name=>"Can the Sun Be Your Enemy", :url=>"catalog/openvault:27280"},
        {:name=>"Cannonball Adderley and the Cannonball Express", :url=>"catalog/openvault:44133"},
        {:name=>"Cannonball Express", :url=>"catalog/openvault:11063"},
        {:name=>"Carew Film Festival", :url=>"catalog/openvault:17527"},
        {:name=>"Community in Action", :url=>"catalog/openvault:13626"},
        {:name=>"Concerts in Black and Brown", :url=>"catalog/openvault:27401"},
        {:name=>"Cost of a Facelift", :url=>"catalog/openvault:17425"},
        {:name=>"Curtis Mayfield and The Impressions perform \"We're A Winner\"", :url=>"catalog/openvault:44002"},
        {:name=>"Dinah Washington", :url=>"catalog/openvault:18378"},
        {:name=>"Evening with Eartha Kitt, An", :url=>"catalog/openvault:26306"},
        {:name=>"Evening with Melvin Van Peebles and Dick Gregory", :url=>"catalog/openvault:17935"},
        {:name=>"Excursion with Tumbao, An", :url=>"catalog/openvault:18058"},
        {:name=>"Great, Great Grandmothers", :url=>"catalog/openvault:15379"},
        {:name=>"Howlin' Wolf", :url=>"catalog/openvault:22369"},
        {:name=>"Howlin' Wolf in concert", :url=>"catalog/openvault:44074"},
        {:name=>"Jazz", :url=>"catalog/openvault:16324"},
        {:name=>"Larry Johnson and Jack Jackson perform \"John Henry\"", :url=>"catalog/openvault:44079"},
        {:name=>"Mississippi Fred MacDowell", :url=>"catalog/openvault:44019"},
        {:name=>"Music Special", :url=>"catalog/openvault:25232"},
        {:name=>"Mystic Chain", :url=>"catalog/openvault:6500"},
        {:name=>"Night of the Blues, A", :url=>"catalog/openvault:15380"},
        {:name=>"Odetta", :url=>"catalog/openvault:15062"},
        {:name=>"Orchestra Pabon in concert", :url=>"catalog/openvault:44050"},
        {:name=>"Percussions", :url=>"catalog/openvault:6647"},
        {:name=>"Pianist Randy Weston performs \"The Healers\"", :url=>"catalog/openvault:44125"},
        {:name=>"Point of View, A", :url=>"catalog/openvault:6773"},
        {:name=>"Public Housing", :url=>"catalog/openvault:19673"},
        {:name=>"Reggae: A Caribbean Cultural Explosion", :url=>"catalog/openvault:9853"},
        {:name=>"Remembering the Savoy Cafe", :url=>"catalog/openvault:44043"},
        {:name=>"Ronald Ingram Gospel chorus", :url=>"catalog/openvault:43974"},
        {:name=>"Ronnie Laws and Pressure", :url=>"catalog/openvault:8552"},
        {:name=>"Roots Music", :url=>"catalog/openvault:10554"},
        {:name=>"Say Brother 15th Anniversary Gala Celebration", :url=>"catalog/openvault:23798"},
        {:name=>"Say Brother 1st Anniversary Show", :url=>"catalog/openvault:26031"},
        {:name=>"Say Brother Presents Message to the People featuring Brown Sugar", :url=>"catalog/openvault:19564"},
        {:name=>"Senior Citizens", :url=>"catalog/openvault:12518"},
        {:name=>"Slices of Black Theatre", :url=>"catalog/openvault:15792"},
        {:name=>"Solar Visions", :url=>"catalog/openvault:26271"},
        {:name=>"Solar Visions performing live in Say Brother studio", :url=>"catalog/openvault:44023"},
        {:name=>"Spring Special", :url=>"catalog/openvault:13825"},
        {:name=>"Street Dancers Bash", :url=>"catalog/openvault:13880"},
        {:name=>"Street Dancers Bash rehearsing the song \"Runnin\"", :url=>"catalog/openvault:44052"},
        {:name=>"Sunfire perform \"Soka Jame\" in the Say Brother studio", :url=>"catalog/openvault:43915"},
        {:name=>"Survival on Mother's Island", :url=>"catalog/openvault:11862"},
        {:name=>"Tavares", :url=>"catalog/openvault:18737"},
        {:name=>"Third World Potpourri", :url=>"catalog/openvault:27068"},
        {:name=>"Vaudeville", :url=>"catalog/openvault:16855"},
        {:name=>"Winter Special", :url=>"catalog/openvault:26057"}
      ]
    end
  end
end