module ExhibitsData
  module Vietnam
    def self.interviews
      [
        {name: "Nguyen Thi Binh", first: "vietnam-1dbd9d-interview-with-nguyen-thi-binh-1981", rest: []},
        {name: "Michael J. Mike Connors", first: "vietnam-38a2e0-interview-with-michael-j-mike-connors-1981", rest: []},
        {name: "Leslie H. Gelb", first: "vietnam-48133e-interview-with-leslie-h-gelb-1982", rest: []},
        {name: "Dang Xuan Teo", first: "vietnam-d7c86f-interview-with-dang-xuan-teo-1981", rest: []},
        {name: "Lloyd M. Mike Rives", first: "vietnam-7cf4bd-interview-with-lloyd-m-mike-rives-1982", rest: []},
        {name: "Phillip Key", first: "vietnam-933ca3-interview-with-phillip-key-1981", rest: []},
        {name: "Young Vietnamese Boys", first: "vietnam-3271f3-interview-with-young-vietnamese-boys-1981", rest: []},
        {name: "William P. Bundy", first: "vietnam-0a7751-interview-with-william-p-bundy-1981", rest: []},
        {name: "Paul N. Mccloskey", first: "vietnam-834453-interview-with-paul-n-mccloskey-1981", rest: []},
        {name: "Archimedes L. A. Patti", first: "vietnam-bf3262-interview-with-archimedes-l-a-patti-1981", rest: []},
        {name: "Ton That Tung", first: "vietnam-4798f7-interview-with-ton-that-tung-1981", rest: []},
        {name: "Nguyen Khanh", first: "vietnam-f2fe66-interview-with-nguyen-khanh-1981", rest: []},
        {name: "Chhang Song", first: "vietnam-57f60b-interview-with-chhang-song", rest: []},
        {name: "William Childs Westmoreland", first: "vietnam-b463a4-interview-with-william-c-william-childs-westmoreland-1981", rest: []},
        {name: "Clark M. Clifford", first: "vietnam-4bf800-interview-with-clark-m-clifford-1981", rest: []},
        {name: "Tran Thi Truyen", first: "vietnam-72c7c8-interview-with-tran-thi-truyen-1981", rest: []},
        {name: "Lucien Conein", first: "vietnam-3abc7d-interview-with-lucien-conein-1981", rest: []},
        {name: "Melvin R. Laird", first: "vietnam-e4f1a1-interview-with-melvin-r-laird-1981", rest: []},
        {name: "Nguyen Thi Te", first: "vietnam-e09f9c-interview-with-nguyen-thi-te-1981", rest: []},
        {name: "Wayne Smith", first: "vietnam-7e3834-interview-with-wayne-smith-1982", rest: []},
        {name: "Harry Mcpherson", first: "vietnam-000f9b-interview-with-harry-mcpherson-1981", rest: []},
        {name: "Jack Keegan", first: "vietnam-d12094-interview-with-jack-keegan-1981", rest: []},
        {name: "William R. Corson", first: "vietnam-0ab374-interview-with-william-r-corson-1982", rest: []},
        {name: "Hoang Phu Ngoc Tuong", first: "vietnam-3fe9ec-interview-with-hoang-phu-ngoc-tuong-1982", rest: []},
        {name: "George Christian", first: "vietnam-ec7509-interview-with-george-christian-1981", rest: []},
        {name: "Dao Vien Trung", first: "vietnam-d37bd9-interview-with-dao-vien-trung-1981", rest: []},
        {name: "Bill D. Moyers", first: "vietnam-369379-interview-with-bill-d-moyers-1981", rest: []},
        {name: "Ama Hoa", first: "vietnam-eb3c84-interview-with-ama-hoa-1981", rest: []},
        {name: "Abbott Low Moffat", first: "vietnam-8a2551-interview-with-abbott-low-moffat-1982", rest: []},
        {name: "Thu Van", first: "vietnam-ffee91-interview-with-thu-van-1981", rest: []},
        {name: "Jonathan F. Jonathan Fredric Ladd", first: "vietnam-b2ee43-interview-with-jonathan-f-jonathan-fredric-ladd-1982", rest: []},
        {name: "Ho Minh Sac", first: "vietnam-3e5493-interview-with-ho-minh-sac-1981", rest: []},
        {name: "Nguyen Phan Phuc", first: "vietnam-886616-interview-with-nguyen-phan-phuc-1981", rest: []},
        {name: "John D. Negroponte", first: "vietnam-1a818d-interview-with-john-d-negroponte-1981", rest: []},
        {name: "H. Bot Adrong", first: "vietnam-62611d-interview-with-h-bot-adrong-1981", rest: []},
        {name: "Jack Valenti", first: "vietnam-9ce4c1-interview-with-jack-valenti-1981", rest: []},
        {name: "Nguyen Thi Hoa", first: "vietnam-462be3-interview-with-nguyen-thi-hoa-1981", rest: []},
        {name: "Dang Van Son", first: "vietnam-dcc279-interview-with-dang-van-son-1981", rest: []},
        {name: "Chhit Do", first: "vietnam-9d1903-interview-with-chhit-do-1982", rest: []},
        {name: "Douglas Kinnard", first: "vietnam-f17174-interview-with-douglas-kinnard-1982", rest: []},
        {name: "William Sloane Coffin", first: "vietnam-35b1e5-interview-with-william-sloane-coffin-1982", rest: []},
        {name: "Pham Thi Xuan Que", first: "vietnam-9a446d-interview-with-pham-thi-xuan-que-1981", rest: []},
        {name: "Everett Bumgardner", first: "vietnam-7d0a90-interview-with-everett-bumgardner-1-1981",
          rest: ["vietnam-d6ffa3-interview-with-everett-bumgardner-2-1982"]
        },
        {name: "Vietnamese Museum Guide", first: "vietnam-c17403-interview-with-vietnamese-museum-guide-1981", rest: []},
        {name: "George W. Ball", first: "vietnam-5e228c-interview-with-george-w-ball-1981", rest: []},
        {name: "Richard M. Moose", first: "vietnam-b44658-interview-with-richard-m-moose-1981", rest: []},
        {name: "Nguyen Van Nghi", first: "vietnam-ef85e3-interview-with-nguyen-van-nghi-1981", rest: []},
        {name: "John Kerry", first: "vietnam-306cf2-interview-with-john-kerry-1982", rest: []},
        {name: "Eugene J. Mccarthy", first: "vietnam-dd4bf1-interview-with-eugene-j-mccarthy-1982", rest: []},
        {name: "Scott Camil", first: "vietnam-61becc-interview-with-scott-camil-1981", rest: []},
        {name: "Van Tien Dung", first: "vietnam-e78a5e-interview-with-van-tien-dung-1981", rest: []},
        {name: "Pham Van Dong", first: "vietnam-df9fbf-interview-with-pham-van-dong-1981", rest: []},
        {name: "Ngo Minh Khoi", first: "vietnam-53e733-interview-with-ngo-minh-khoi-1981", rest: []},
        {name: "Mrs Ngo Ba Thanh", first: "vietnam-0bb668-interview-with-mrs-ngo-ba-thanh-1981", rest: []},
        {name: "Vu Quoc Uy", first: "vietnam-d4ea0b-interview-with-vu-quoc-uy-1981", rest: []},
        {name: "Bayard Rustin", first: "vietnam-a3b1e1-interview-with-bayard-rustin-1982", rest: []},
        {name: "Jane Barton", first: "vietnam-af4a30-interview-with-jane-barton-1981", rest: []},
        {name: "Nguyen Luan", first: "vietnam-81880e-interview-with-nguyen-luan-1981", rest: []},
        {name: "Nguyen Huu Hanh", first: "vietnam-8289ff-interview-with-nguyen-huu-hanh-1981", rest: []},
        {name: "Hoang Loc", first: "vietnam-fd3529-interview-with-hoang-loc-1981", rest: []},
        {name: "L. Dean Brown", first: "vietnam-94361b-interview-with-l-dean-brown-1981", rest: []},
        {name: "Ngo Minh Kha", first: "vietnam-4e201a-interview-with-ngo-minh-kha-1981", rest: []},
        {name: "Huynh Van Tieng", first: "vietnam-774f8d-interview-with-huynh-van-tieng-1981", rest: []},
        {name: "J. Vinton Lawrence", first: "vietnam-fae359-interview-with-j-vinton-vint-lawrence-1981", rest: []},
        {name: "Frederick G. Dutton", first: "vietnam-478315-interview-with-frederick-g-dutton-1981", rest: []},
        {name: "Richard C. Holbrooke (part 2)", first: "vietnam-019ef6-interview-with-richard-c-holbrooke-2-1982", rest: []},
        {name: "Tran Duy Hung", first: "vietnam-1937cc-interview-with-tran-duy-hung-1981", rest: []},
        {name: "Jack Hill", first: "vietnam-cc6145-interview-with-jack-hill-1982", rest: []},
        {name: "Raymond K. Raymond Kissam Price", first: "vietnam-eb0026-interview-with-raymond-k-raymond-kissam-price-1982", rest: []},
        {name: "Paul M. Kattenburg", first: "vietnam-f47e46-interview-with-paul-m-kattenburg-1981", rest: []},
        {name: "Le Minh Dao", first: "vietnam-2ecd26-interview-with-le-minh-dao-1981", rest: []},
        {name: "George Cantero", first: "vietnam-52aad2-interview-with-george-cantero-1981", rest: []},
        {name: "Tuu Ky", first: "vietnam-2ab2d9-interview-with-tuu-ky-1981", rest: []},
        {name: "Nguyen Thi Nguyet Anh", first: "vietnam-ac000f-interview-with-nguyen-thi-nguyet-anh-1981", rest: []},
        {name: "Duong Van Khang", first: "vietnam-6adbe2-interview-with-duong-van-khang-1981", rest: []},
        {name: "Le Tran Nhan", first: "vietnam-c30e89-interview-with-le-tran-nhan-1981", rest: []},
        {name: "Sam Brown", first: "vietnam-5f3845-interview-with-sam-brown-1982", rest: []},
        {name: "Tran Van Nhut", first: "vietnam-5edaef-interview-with-tran-van-nhut-1981", rest: []},
        {name: "Hoang Thi Dan", first: "vietnam-1cdfee-interview-with-hoang-thi-dan-1981", rest: []},
        {name: "Nguyen Thi Mai", first: "vietnam-f8daaf-interview-with-nguyen-thi-mai-1981", rest: []},
        {name: "Madame Ngo Dinh Nhu", first: "vietnam-1a3f8e-interview-with-madame-ngo-dinh-nhu-1982", rest: []},
        {name: "Hoang Thi Thu", first: "vietnam-c4d87f-interview-with-hoang-thi-thu-1981", rest: []},
        {name: "Nguyen Manh Ai", first: "vietnam-5ac0b6-interview-with-nguyen-manh-ai-1981", rest: []},
        {name: "Douglas MacArthur", first: "vietnam-4ab69e-interview-with-douglas-macarthur-1982", rest: []},
        {name: "Ho Thanh Dam", first: "vietnam-1bca76-interview-with-ho-thanh-dam-1981", rest: []},
        {name: "Nguyen Van Binh", first: "vietnam-ffa41d-interview-with-nguyen-van-binh-1981", rest: []},
        {name: "Duong Long Sang", first: "vietnam-3203c6-interview-with-duong-long-sang-1981", rest: []},
        {name: "Robert J. Bobfranco", first: "vietnam-8a3c98-interview-with-robert-j-bob-franco", rest: []},
        {name: "McGeorge Bundy", first: "vietnam-c224f2-interview-with-mcgeorge-bundy", rest: []},
        {name: "Frank Fred Hickey", first: "vietnam-b0f9b2-interview-with-frank-fred-hickey-1981", rest: []},
        {name: "William Egan Colby", first: "vietnam-4e3224-interview-with-william-egan-colby-1981", rest: []},
        {name: "Nguyen Huu Tho", first: "vietnam-3443d8-interview-with-nguyen-huu-tho-1981", rest: []},
        {name: "Nguyen Bay", first: "vietnam-9442ef-interview-with-nguyen-bay-1981", rest: []},
        {name: "Le Thi Ma", first: "vietnam-5f0a21-interview-with-le-thi-ma-1981", rest: []},
        {name: "Tran Thi My", first: "vietnam-0b2012-interview-with-tran-thi-my-1981", rest: []},
        {name: "Morton H. Halperin", first: "vietnam-386950-interview-with-morton-h-halperin-1981", rest: []},
        {name: "Tran Van Lai", first: "vietnam-767cb6-interview-with-tran-van-lai-1981", rest: []},
        {name: "Le Lam", first: "vietnam-e080e1-interview-with-le-lam-1981", rest: []},
        {name: "Do Cuong", first: "vietnam-470cbc-interview-with-do-cuong-1981", rest: []},
        {name: "Hoang Anh Tuan", first: "vietnam-a8155e-interview-with-hoang-anh-tuan-1981", rest: []},
        {name: "Doidge Estcourt Taunton", first: "vietnam-803ba6-interview-with-doidge-estcourt-taunton-1982", rest: []},
        {name: "Thomas H. Moorer", first: "vietnam-59ce8c-interview-with-thomas-h-moorer-1981", rest: []},
        {name: "Pierrebrochand", first: "vietnam-b73429-interview-with-pierre-brochand", rest: []},
        {name: "Kenneth Moorefield", first: "vietnam-c82024-interview-with-kenneth-moorefield-1981", rest: []},
        {name: "Nguyen Thi Sinh", first: "vietnam-1fe036-interview-with-nguyen-thi-sinh-1981", rest: []},
        {name: "Nguyen Huu Nhan", first: "vietnam-846229-interview-with-nguyen-huu-nhan-1981", rest: []},
        {name: "David T. Dellinger", first: "vietnam-6cba85-interview-with-david-t-dellinger-1982", rest: []},
        {name: "Nguyen Cong Thanh", first: "vietnam-34e4d9-interview-with-nguyen-cong-thanh-1981", rest: []},
        {name: "John Chancellor", first: "vietnam-f269d9-interview-with-john-chancellor-1982", rest: []},
        {name: "Peter Paulmahoney", first: "vietnam-13d816-interview-with-peter-paul-mahoney", rest: []},
        {name: "Le Thi Ton", first: "vietnam-6c549d-interview-with-le-thi-ton-1981", rest: []},
        {name: "Nguyen Si Que", first: "vietnam-4f16c1-interview-with-nguyen-si-que-1981", rest: []},
        {name: "Bui Diem", first: "vietnam-6ed7f9-interview-with-bui-diem-1-1981",
          rest: ["vietnam-3152dc-interview-with-bui-diem-2-1981"]
        },
        {name: "Hoang Duc Nha", first: "vietnam-35c9b1-interview-with-hoang-duc-nha-1-1981", rest: []},
        {name: "Nguyen Cao Ky", first: "vietnam-931335-interview-with-nguyen-cao-ky-1981", rest: []},
        {name: "Ray S. Cline", first: "vietnam-bbff34-interview-with-ray-s-cline-1982", rest: []},
        {name: "Le Van Phuc", first: "vietnam-29f4cd-interview-with-le-van-phuc-1981", rest: []},
        {name: "Horace W. Busby", first: "vietnam-fa3035-interview-with-horace-w-busby-1981", rest: []},
        {name: "Hoang Duc Nha", first: "vietnam-2dd99e-interview-with-hoang-duc-nha-2-1981", rest: []},
        {name: "Francois Ponchaud", first: "vietnam-2be511-interview-with-francois-ponchaud-1982", rest: []},
        {name: "Frederick Nolting", first: "vietnam-454634-interview-with-frederick-nolting-1981", rest: []},
        {name: "Mrs Nguyen Congminh", first: "vietnam-43b0a0-interview-with-mrs-nguyen-cong-minh", rest: []},
        {name: "Lam Son Nao", first: "vietnam-28d91f-interview-with-lam-son-nao-1981", rest: []},
        {name: "Nguyen Thi Tuyet", first: "vietnam-770459-interview-with-nguyen-thi-tuyet-1981", rest: []},
        {name: "Hoang Quoc Viet", first: "vietnam-b91a7c-interview-with-hoang-quoc-viet-1981", rest: []},
        {name: "Le Van Tri", first: "vietnam-1094ae-interview-with-le-van-tri-1981", rest: []},
        {name: "John James Flynt Jr." , first: "vietnam-723591-interview-with-john-james-flynt-jr-1982", rest: []},
        {name: "Herbert Bluechel", first: "vietnam-e01ec4-interview-with-herbert-bluechel-1981", rest: []},
        {name: "Nguyen Cong Danh", first: "vietnam-d87012-interview-with-nguyen-cong-danh-1981", rest: []},
        {name: "Philip Geoffrey Malins", first: "vietnam-164308-interview-with-philip-geoffrey-malins-1982", rest: []},
        {name: "Sisouk Na Champassak", first: "vietnam-557711-interview-with-sisouk-na-champassak-1982", rest: []},
        {name: "Le Van Ba", first: "vietnam-0eb6d9-interview-with-le-van-ba-1981", rest: []},
        {name: "Nguyen Khac Ham", first: "vietnam-b2e4a5-interview-with-nguyen-khac-ham-1981", rest: []},
        {name: "Sok Sarren", first: "vietnam-467d30-interview-with-sok-sarren-1982", rest: []},
        {name: "Tran Vi Truong", first: "vietnam-943c96-interview-with-tran-vi-truong-1981", rest: []},
        {name: "Phung The Tai", first: "vietnam-21f0b4-interview-with-phung-the-tai-1981", rest: []},
        {name: "Tomlyons", first: "vietnam-a957b5-interview-with-tom-lyons", rest: []},
        {name: "Nguyen Co Thach", first: "vietnam-7699e6-interview-with-nguyen-co-thach-1981", rest: []},
        {name: "Nguyen Tat Dat", first: "vietnam-e1ea29-interview-with-nguyen-tat-dat-1981", rest: []},
        {name: "Ngo Thi Hien", first: "vietnam-60ee60-interview-with-ngo-thi-hien-1981", rest: []},
        {name: "Pengthuon", first: "vietnam-7b0ea1-interview-with-peng-thuon", rest: []},
        {name: "Phung Thi Tiem", first: "vietnam-b427ab-interview-with-phung-thi-tiem-1981", rest: []},
        {name: "Le Cong Chinh (part 2)", first: "vietnam-d145a9-interview-with-le-cong-chinh-2-1981", rest: []},
        {name: "Phuong Nam", first: "vietnam-6048eb-interview-with-phuong-nam-1981", rest: []},
        {name: "William H. William Healy Sullivan", first: "vietnam-fe59dc-interview-with-william-h-william-healy-sullivan-1981", rest: []},
        {name: "James M. Fallows", first: "vietnam-209caf-interview-with-james-m-fallows-1982", rest: []},
        {name: "Tran Ding Thong", first: "vietnam-9839f7-interview-with-tran-ding-thong-1981", rest: []},
        {name: "Tho Hang", first: "vietnam-a68b58-interview-with-tho-hang-1-1981",
          rest: ["vietnam-1eb64e-interview-with-tho-hang-2-1981"]
        },
        {name: "Frank Snepp", first: "vietnam-501236-interview-with-frank-snepp-1981", rest: []},
        {name: "Pham Thanh Gion", first: "vietnam-539a4c-interview-with-pham-thanh-gion-1981", rest: []},
        {name: "Tran Do", first: "vietnam-8915b6-interview-with-tran-do-1981", rest: []},
        {name: "Nguyen Thi Ngo", first: "vietnam-975432-interview-with-nguyen-thi-ngo-1981", rest: []},
        {name: "Nguyen Thi Cao", first: "vietnam-9d953e-interview-with-nguyen-thi-cao-1981", rest: []},
        {name: "Tran Vandon", first: "vietnam-b01a66-interview-with-tran-van-don", rest: []},
        {name: "Pham Van Thu", first: "vietnam-87380c-interview-with-pham-van-thu-1981", rest: []},
        {name: "Roger Hilsman", first: "vietnam-c3d5d3-interview-with-roger-hilsman-1981", rest: []},
        {name: "Nguyen Van", first: "vietnam-4c8279-interview-with-nguyen-van-1981", rest: []},
        {name: "Nguyen Thi Trong", first: "vietnam-22e706-interview-with-nguyen-thi-trong-1981", rest: []},
        {name: "Woman In Street", first: "vietnam-5c1f3c-interview-with-woman-in-street-1981", rest: []},
        {name: "Cao Xuan Nghia", first: "vietnam-762429-interview-with-cao-xuan-nghia-1981", rest: []},
        {name: "Thich Minh Chau", first: "vietnam-101322-interview-with-thich-minh-chau-1981", rest: []},
        {name: "Nham Cam", first: "vietnam-0dfb8e-interview-with-nham-cam-1981", rest: []},
        {name: "Edward J. Banks", first: "vietnam-12991e-interview-with-edward-j-banks-1982", rest: []},
        {name: "Tran Van Ngo", first: "vietnam-094e1e-interview-with-tran-van-ngo-1981", rest: []},
        {name: "Y True Nie", first: "vietnam-ba3f2d-interview-with-y-true-nie-1981", rest: []},
        {name: "Nguyen Thi Duc", first: "vietnam-d51556-interview-with-nguyen-thi-duc-1981", rest: []},
        {name: "Tran Thi Giai", first: "vietnam-76fb17-interview-with-tran-thi-giai-1981", rest: []},
        {name: "Dean Rusk", first: "vietnam-58a64d-interview-with-dean-rusk-2-1981", rest: []},
        {name: "Nguyen Thanh Xuan", first: "vietnam-75fa47-interview-with-nguyen-thanh-xuan-1981", rest: []},
        {name: "Robinson Risner", first: "vietnam-0b40bf-interview-with-robinson-risner-1981", rest: []},
        {name: "Ray Snyder", first: "vietnam-839fcc-interview-with-ray-snyder-1981", rest: []},
        {name: "Nguyen Thi Thiep", first: "vietnam-d3ee9a-interview-with-nguyen-thi-thiep-1981", rest: []},
        {name: "Duong Thi My Trung", first: "vietnam-643281-interview-with-duong-thi-my-trung-1981", rest: []},
        {name: "Tran Ngocluong", first: "vietnam-12c023-interview-with-tran-ngoc-luong", rest: []},
        {name: "Carleton Swift", first: "vietnam-9dc948-interview-with-carleton-swift", rest: []},
        {name: "Thich Tri Thu", first: "vietnam-e52827-interview-with-thich-tri-thu-1981", rest: []},
        {name: "Phan Phung Tien", first: "vietnam-856d86-interview-with-phan-phung-tien-1981", rest: []},
        {name: "Ralph C. Thomas III", first: "vietnam-c344d8-interview-with-ralph-c-thomas-iii-1981", rest: []},
        {name: "Thruong Yem", first: "vietnam-1cfa79-interview-with-thruong-yem-1981", rest: []},
        {name: "Everett Alvarez", first: "vietnam-fd03ef-interview-with-everett-alvarez-1981", rest: []},
        {name: "Y Luong Bya", first: "vietnam-45718a-interview-with-y-luong-bya-1981", rest: []},
        {name: "Charles Sabatier", first: "vietnam-c7c7c9-interview-with-charles-sabatier-1982-part-1-of-2",
          rest: [ "vietnam-eebf58-interview-with-charles-sabatier-1982-part-2-of-2"
          ]
        },
        {name: "Thich Tu Hanh", first: "vietnam-82584c-interview-with-thich-tu-hanh-1981", rest: []},
        {name: "Vo Van Nhung", first: "vietnam-b1ba00-interview-with-vo-van-nhung-1981", rest: []},
        {name: "Ural Alexis Johnson", first: "vietnam-8372ad-interview-with-u-alexis-ural-alexis-johnson-1982", rest: []},
        {name: "Tran Ngoc Lieng", first: "vietnam-f113a8-interview-with-tran-ngoc-lieng-1981", rest: []},
        {name: "Y Bloc", first: "vietnam-3ff8fe-interview-with-y-bloc-1981", rest: []},
        {name: "Le Dinh Hy", first: "vietnam-efa891-interview-with-le-dinh-hy-1981", rest: []},
        {name: "Tran Nhat Bang", first: "vietnam-e1e580-interview-with-tran-nhat-bang-1981", rest: []},
        {name: "James Claude Thomson", first: "vietnam-cda8e9-interview-with-james-claude-thomson-1981", rest: []},
        {name: "Thuong Thi Mai", first: "vietnam-ad8dda-interview-with-thuong-thi-mai-1981", rest: []},
        {name: "Frank M. White", first: "vietnam-213564-interview-with-frank-m-white-1981", rest: []},
        {name: "Nguyen Huu", first: "vietnam-64bf4f-interview-with-nguyen-huu-1981", rest: []},
        {name: "Pham Duy", first: "vietnam-b19ea1-interview-with-pham-duy-1982", rest: []},
        {name: "Bui Tin", first: "vietnam-f8ca90-interview-with-bui-tin-1-1981",
          rest: ["vietnam-f729b0-interview-with-bui-tin-2-1981"]
        },
        {name: "Walt Whitman Rostow", first: "vietnam-c8f4ed-interview-with-w-w-walt-whitman-rostow-1981", rest: []},
        {name: "Madame Duong Van Khang", first: "vietnam-42008e-interview-with-madame-duong-van-khang-1981", rest: []},
        {name: "William Averell Harriman", first: "vietnam-436bdd-interview-with-w-averell-william-averell-harriman-1979-part-1-of-4",
          rest: [ "vietnam-e996c7-interview-with-w-averell-william-averell-harriman-1979-part-2-of-4", "vietnam-dff8f9-interview-with-w-averell-william-averell-harriman-1979-part-3-of-4", "vietnam-66ca94-interview-with-w-averell-william-averell-harriman-1979-part-4-of-4"
          ]
        },
        {name: "Do Thi Bay", first: "vietnam-cac6a5-interview-with-do-thi-bay-1981", rest: []},
        {name: "J. Lawton Collins", first: "vietnam-264d70-interview-with-j-lawton-collins-1981", rest: []},
        {name: "Ngo Dinhluyen", first: "vietnam-0c7985-interview-with-ngo-dinh-luyen", rest: []},
        {name: "Ton That Thien", first: "vietnam-18db13-interview-with-ton-that-thien-1981", rest: []},
        {name: "R. W. Komer", first: "vietnam-0194f2-interview-with-r-w-komer-1982", rest: []},
        {name: "Henry Kissinger", first: "vietnam-ce422e-interview-with-henry-kissinger-1982", rest: []},
        {name: "William E. Le Gro", first: "vietnam-e7fe8a-interview-with-william-e-le-gro-1981", rest: []},
        {name: "Gerald R. Ford", first: "vietnam-de3a13-interview-with-gerald-r-ford-1982", rest: []},
        {name: "Paul C. Warnke", first: "vietnam-050761-interview-with-paul-c-warnke-1982", rest: []},
        {name: "Earl Young", first: "vietnam-03e0bb-interview-with-earl-young-1981", rest: []},
        {name: "Dean Rusk", first: "vietnam-6f0280-interview-with-dean-rusk-1-1982", rest: []},
        {name: "Eldridge Durbrow", first: "vietnam-078fff-interview-with-eldridge-durbrow-1979-part-1-of-2",
          rest: [ "vietnam-2eb162-interview-with-eldridge-durbrow-1979-part-2-of-2"
          ]
        },
        {name: "Myron Harrington", first: "vietnam-de0a9d-interview-with-myron-harrington-1981", rest: []},
        {name: "Henry Cabot Lodge", first: "vietnam-b93dd4-interview-with-henry-cabot-lodge-1979-part-1-of-5",
          rest: [ "vietnam-dbabfd-interview-with-henry-cabot-lodge-1979-part-2-of-5", "vietnam-228c4a-interview-with-henry-cabot-lodge-1979-part-3-of-5", "vietnam-0122cd-interview-with-henry-cabot-lodge-1979-part-4-of-5", "vietnam-83f288-interview-with-henry-cabot-lodge-1979-part-5-of-5"
          ]
        },
        {name: "Carl F. Bernard", first: "vietnam-16d140-interview-with-carl-f-bernard-1981", rest: []},
        {name: "Edward Geary Lansdale", first: "vietnam-f1001a-interview-with-edward-geary-lansdale-1979-part-1-of-5",
          rest: [ "vietnam-8fe831-interview-with-edward-geary-lansdale-1979-part-2-of-5", "vietnam-4ba46a-interview-with-edward-geary-lansdale-1979-part-3-of-5", "vietnam-2f8f83-interview-with-edward-geary-lansdale-1979-part-4-of-5", "vietnam-a9fa62-interview-with-edward-geary-lansdale-1979-part-5-of-5"
          ]
        },
        {name: "Tran Thi Tuyet", first: "vietnam-88b680-interview-with-tran-thi-tuyet-1981", rest: []},
        {name: "Nguyen Ky", first: "vietnam-7c2879-interview-with-nguyen-ky-1981", rest: []},
        {name: "Maxwell Davenport Taylor", first: "vietnam-f7ff45-interview-with-maxwell-d-maxwell-davenport-taylor-1979-part-1-of-4",
          rest: [ "vietnam-b063c6-interview-with-maxwell-d-maxwell-davenport-taylor-1979-part-2-of-4", "vietnam-24d1db-interview-with-maxwell-d-maxwell-davenport-taylor-1979-part-3-of-4", "vietnam-188cda-interview-with-maxwell-d-maxwell-davenport-taylor-1979-part-4-of-4"
          ]
        },
        {name: "Nguyen Chi Thanh", first: "vietnam-f74415-interview-with-nguyen-chi-thanh-1981", rest: []},
        {name: "Nguyen Thinhi", first: "vietnam-5456ea-interview-with-nguyen-thi-nhi", rest: []},
        {name: "David Harris", first: "vietnam-08d0a8-interview-with-david-harris-1982", rest: []},
        {name: "David Halberstam", first: "vietnam-86e38f-interview-with-david-halberstam-1979-part-1-of-5",
          rest: [ "vietnam-cbedc8-interview-with-david-halberstam-1979-part-2-of-5", "vietnam-ae77bf-interview-with-david-halberstam-1979-part-3-of-5", "vietnam-f13fc4-interview-with-david-halberstam-1979-part-4-of-5", "vietnam-2602a8-interview-with-david-halberstam-1979-part-5-of-5"
          ]
        },
        {name: "Lucien Bodard", first: "vietnam-4867ab-interview-with-lucien-bodard-1981", rest: []},
        {name: "Ngo Thi Tan", first: "vietnam-b18d7f-interview-with-ngo-thi-tan-1981", rest: []},
        {name: "Robert Montague (audio only)", first: "vietnam-e5b3d3-interview-with-robert-montague-1982", rest: []},
        {name: "Phuong Doan (audio only)", first: "vietnam-bab15f-interview-with-phuong-doan-1983", rest: []},
        {name: "Gillespie V. Montgomery (audio only)", first: "vietnam-068767-interview-with-g-v-gillespie-v-montgomery-1983", rest: []},
        {name: "Arthur Egendorf (audio only)", first: "vietnam-02f66a-interview-with-arthur-egendorf-1983", rest: []},
        {name: "John Wheeler (audio only)", first: "vietnam-c9d95f-interview-with-john-wheeler-1981", rest: []},
        {name: "David Christian (audio only)", first: "vietnam-6891de-interview-with-david-christian-1983", rest: []},
        {name: "Harold Robert Isaacs (audio only)", first: "vietnam-83910d-interview-with-harold-robert-isaacs-1981", rest: []},
        {name: "Richard C. Holbrooke (part 1 - audio only)", first: "vietnam-6c7004-interview-with-richard-c-holbrooke-1-1983", rest: []},
        {name: "David R. Hawk (audio only)", first: "vietnam-5dc58b-interview-with-david-r-hawk-1983", rest: []},
        {name: "Maureen Hatch (audio only)", first: "vietnam-5c031c-interview-with-maureen-hatch-1983", rest: []},
        {name: "Dith Pran (audio only)", first: "vietnam-7ab1a2-interview-with-dith-pran-1983", rest: []},
        {name: "Greg Kane (audio only)", first: "vietnam-f3de53-interview-with-greg-kane-1983", rest: []},
        {name: "Muoi Van Nguyen (audio only)", first: "vietnam-af8d79-interview-with-muoi-van-nguyen-1983", rest: []},
        {name: "Edward C. Meyer", first: "vietnam-d325e6-interview-with-edward-c-meyer", rest: []},
        {name: "Nguyen Minh", first: "vietnam-fa23c2-interview-with-nguyen-minh", rest: []},
        {name: "Zbigniew Brzezinski (audio only)", first: "vietnam-fc1f9b-interview-with-zbigniew-brzezinski-1983", rest: []},
        {name: "Stephen J. Solarz (audio only)", first: "vietnam-4f99ee-interview-with-stephen-j-solarz-1983", rest: []},
        {name: "Le Cong Chinh (part 1 - audio only)", first: "vietnam-8903eb-interview-with-le-cong-chinh-1-1981", rest: []},
        {name: "Bob Muller (audio only)", first: "vietnam-3eef1c-interview-with-bob-muller-1983", rest: []},
        {name: "Mary Truong", first: "vietnam-ce6b38-interview-with-mary-truong", rest: []},
        {name: "Nguyen Tinh", first: "vietnam-dd6e8f-interview-with-nguyen-tinh", rest: []},
        {name: "Long Duong (audio only)", first: "vietnam-228ae7-interview-with-long-duong-1983", rest: []},
        {name: "Mark Leighton (audio only)", first: "vietnam-d90da9-interview-with-mark-leighton-1983", rest: []},
        {name: "Indor Jag Mohan (audio only)", first: "vietnam-b8d73b-interview-with-indor-jag-mohan-1981", rest: []},
        {name: "Robinson Risner (audio only)", first: "471a9e-interview-with-robinson-risner-1981", rest: []},
        {name: "Ted Danielsen (transcript only)", first: "vietnam-89f5a4-interview-with-ted-danielsen-1981", rest: []},
        {name: "Daniel Ellsberg (transcript only)", first: "vietnam-354cac-interview-with-daniel-ellsberg", rest: []},
        {name: "Don Luce (transcript only)", first: "vietnam-edfd42-interview-with-don-luce", rest: []},
        {name: "Orrin DeForest (transcript only)", first: "vietnam-b98ddf-interview-with-orrin-deforest", rest: []},
        {name: "Douglas Hostetter (transcript only)", first: "vietnam-556c2f-interview-with-douglas-hostetter", rest: []},
        {name: "John T. McAllister (transcript only)", first: "vietnam-ec6417-interview-with-john-t-mcallister", rest: []},
        {name: "Astor Rogers (transcript only)", first: "vietnam-288ff4-interview-with-astor-rogers", rest: []},
        {name: "David Ross (transcript only)", first: "vietnam-966e54-interview-with-david-ross", rest: []},
        {name: "James N. Rowe (transcript only)", first: "vietnam-37285a-interview-with-james-n-rowe", rest: []},
        {name: "Tran Ngoc Chau (transcript only)", first: "vietnam-fee2f8-interview-with-tran-ngoc-chau", rest: []},
        {name: "Mark Smith (transcript only)", first: "vietnam-7ebc56-interview-with-mark-smith-1-1982",
          rest: ["vietnam-03128b-interview-with-mark-smith-2"]
        },
        {name: "William D. Ehrhart (transcript only)", first: "vietnam-bca896-interview-with-william-d-ehrhart-1-1982",
          rest: ["vietnam-e2cd2c-interview-with-william-d-ehrhart-2"]
        },
      ].sort_by {|interview| interview[:name] }
    end
  end
end