<% jetty_port = ENV['JETTY_PORT'] || '8983' %>

development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://127.0.0.1:#{jetty_port}/fedora" %>
test: &TEST  
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= "http://127.0.0.1:#{jetty_port}/fedora-test" %>
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora
cucumber:
  <<: *TEST
