require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomCollectionsController do

  # This should return the minimal set of attributes required to create a valid
  # CustomCollection. As you add validations to CustomCollection, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    attributes_for(:custom_collection)
  end

  describe "as a scholar" do
    before :each do 
      @user = create(:user, role: 'scholar')
      sign_in @user
    end
    describe "GET index" do
      it "assigns all custom_collections as @custom_collections" do
        custom_collection = CustomCollection.create! valid_attributes
        get :index, {}
        assigns(:custom_collections).should eq([custom_collection])
      end
    end

    describe "GET show" do
      it "assigns the requested custom_collection as @custom_collection" do
        custom_collection = CustomCollection.create! valid_attributes
        get :show, {:id => custom_collection.to_param}
        assigns(:custom_collection).should eq(custom_collection)
      end
    end

    describe "GET new" do
      it "assigns a new custom_collection as @custom_collection" do
        get :new, {}
        assigns(:custom_collection).should be_a_new(CustomCollection)
      end
    end

    describe "GET edit" do
      it "assigns the requested custom_collection as @custom_collection" do
        custom_collection = CustomCollection.create! valid_attributes
        get :edit, {:id => custom_collection.to_param}
        assigns(:custom_collection).should eq(custom_collection)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new CustomCollection" do
          expect {
            post :create, {:custom_collection => valid_attributes}
          }.to change(CustomCollection, :count).by(1)
        end

        it "assigns a newly created custom_collection as @custom_collection" do
          post :create, {:custom_collection => valid_attributes}
          assigns(:custom_collection).should be_a(CustomCollection)
          assigns(:custom_collection).should be_persisted
        end

        it "redirects to the created custom_collection" do
          post :create, {:custom_collection => valid_attributes}
          response.should redirect_to(CustomCollection.last)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved custom_collection as @custom_collection" do
          # Trigger the behavior that occurs when invalid params are submitted
          CustomCollection.any_instance.stub(:save).and_return(false)
          post :create, {:custom_collection => { "name" => "invalid value" }}
          assigns(:custom_collection).should be_a_new(CustomCollection)
        end

        it "re-renders the 'new' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          CustomCollection.any_instance.stub(:save).and_return(false)
          post :create, {:custom_collection => { "name" => "invalid value" }}
          response.should render_template :new
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        it "updates the requested custom_collection" do
          custom_collection = CustomCollection.create! valid_attributes
          # Assuming there are no other custom_collections in the database, this
          # specifies that the CustomCollection created on the previous line
          # receives the :update_attributes message with whatever params are
          # submitted in the request.
          CustomCollection.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
          put :update, {:id => custom_collection.to_param, :custom_collection => { "name" => "MyString" }}
        end

        it "assigns the requested custom_collection as @custom_collection" do
          custom_collection = CustomCollection.create! valid_attributes
          put :update, {:id => custom_collection.to_param, :custom_collection => valid_attributes}
          assigns(:custom_collection).should eq(custom_collection)
        end

        it "redirects to the custom_collection" do
          custom_collection = CustomCollection.create! valid_attributes
          put :update, {:id => custom_collection.to_param, :custom_collection => valid_attributes}
          response.should redirect_to(custom_collection)
        end
      end

      describe "with invalid params" do
        it "assigns the custom_collection as @custom_collection" do
          custom_collection = CustomCollection.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          CustomCollection.any_instance.stub(:save).and_return(false)
          put :update, {:id => custom_collection.to_param, :custom_collection => { "name" => "invalid value" }}
          assigns(:custom_collection).should eq(custom_collection)
        end

        it "re-renders the 'edit' template" do
          custom_collection = CustomCollection.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          CustomCollection.any_instance.stub(:save).and_return(false)
          put :update, {:id => custom_collection.to_param, :custom_collection => { "name" => "invalid value" }}
          response.should render_template("edit")
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested custom_collection" do
        custom_collection = CustomCollection.create! valid_attributes
        expect {
          delete :destroy, {:id => custom_collection.to_param}
        }.to change(CustomCollection, :count).by(-1)
      end

      it "redirects to the custom_collections list" do
        custom_collection = CustomCollection.create! valid_attributes
        delete :destroy, {:id => custom_collection.to_param}
        response.should redirect_to(custom_collections_url)
      end
    end
  end
end
